#!/usr/bin/env bash
# memory-context-refresh.sh — Generate ~/.brain/memory-context.md for passive AI injection
#
# Run nightly by office-nightly-scheduler.sh.
# Output: a compact, always-current summary of the shared memory index + recent facts.
#
# Purpose: Codex and Gemini have no UserPromptSubmit hook mechanism. This file is included
# in their startup configs (AGENTS.md, GEMINI.md) as a passive read at session start —
# no hook needed. Any AI that reads it gets the same memory context as Claude.
#
# Claude Code also benefits: agents spawned via Agent tool don't inherit hook-injected memory.
# They read this file directly if the orchestrating prompt includes it.
#
# Output format: compact markdown, ~1-2k tokens, readable by any AI in a single shot.

set -euo pipefail

MEMORY_DIR="${BRAIN_MEMORY_DIR:-$HOME/.brain/memory}"
OUTPUT_FILE="${MEMORY_CONTEXT_OUTPUT:-$HOME/.brain/memory-context.md}"
FACTS_FILE="$MEMORY_DIR/facts.jsonl"
MEMORY_INDEX="$MEMORY_DIR/MEMORY.md"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Timestamp
generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
generated_local="$(TZ=Europe/Lisbon date '+%Y-%m-%d %H:%M Lisbon')"

# Count entries
entry_count=0
if [ -f "$MEMORY_INDEX" ]; then
  entry_count=$(grep -c "^\- \[mem-" "$MEMORY_INDEX" 2>/dev/null || echo 0)
fi

fact_count=0
active_facts=""
if [ -f "$FACTS_FILE" ]; then
  fact_count=$(grep -c '"valid_to":null' "$FACTS_FILE" 2>/dev/null) || fact_count=0

  # Build compact active facts list (entity | predicate | object)
  while IFS= read -r line; do
    if ! printf '%s' "$line" | grep -q '"valid_to":null'; then
      continue
    fi
    entity=$(printf '%s' "$line" | grep -oE '"entity":"([^"]*)"' | cut -d'"' -f4)
    predicate=$(printf '%s' "$line" | grep -oE '"predicate":"([^"]*)"' | cut -d'"' -f4)
    object=$(printf '%s' "$line" | grep -oE '"object":"([^"]*)"' | cut -d'"' -f4)
    active_facts="${active_facts}- ${entity} | ${predicate} | ${object}
"
  done < "$FACTS_FILE"
fi

# Build full index section
index_section=""
if [ -f "$MEMORY_INDEX" ]; then
  index_section=$(grep "^\- \[mem-" "$MEMORY_INDEX" 2>/dev/null || echo "(no entries)")
fi

# Write output file
cat > "$OUTPUT_FILE" <<EOF
# Memory Context
<!-- Auto-generated by memory-context-refresh.sh — do not edit manually -->
<!-- Generated: ${generated_at} (${generated_local}) -->
<!-- Source: ${MEMORY_DIR} -->

This file is the shared AI memory context. It is regenerated nightly and reflects
the current state of ~/.brain/memory/. Read it at session start for instant context.

To modify memory: use mem-write, mem-facts, or mem-search from the shell.
To query details: mem-search <keyword> or mem-search --id <id>

---

## Memory Index (${entry_count} entries)

${index_section}

---

## Active Facts (${fact_count} facts)

${active_facts:-"(no active facts)"}

---

## How to use this file

Read the index above to know what memories exist. Use the IDs to fetch full content:
\`\`\`bash
mem-search --id mem-project-001   # fetch full content
mem-search <keyword>              # search by topic
mem-facts list Steve              # list facts by entity
\`\`\`

Memory types: user (who Steve is), feedback (how to work), project (current work), ref (external resources).
EOF

echo "Generated $OUTPUT_FILE (entries=$entry_count facts=$fact_count)"
