import type { AgentCapabilitySummary } from './agent-capabilities.js';

const CLI_CAPABILITIES: AgentCapabilitySummary[] = [
  {
    id: 'cli.cloudflare',
    kind: 'cli',
    label: 'Cloudflare CLI',
    source: 'operations/runbooks/cloudflare-deploy.md',
    description: 'Cloudflare tooling for DNS, tunnels, and deployment-related operations.',
    safetyClass: 'external_state',
    requiresApprovalFor: ['dns_change', 'deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'dns', 'deploy'],
    verification: ['cloudflare --help', 'wrangler --version'],
    enabled: true,
  },
  {
    id: 'cli.dokploy',
    kind: 'cli',
    label: 'Dokploy CLI',
    source: 'operations/runbooks/dokploy.md',
    description: 'Dokploy tooling for app deployment and hosting lifecycle management.',
    safetyClass: 'external_state',
    requiresApprovalFor: ['deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'deploy'],
    verification: ['dokploy --help'],
    enabled: true,
  },
  {
    id: 'cli.aws',
    kind: 'cli',
    label: 'AWS CLI',
    source: 'operations/runbooks/aws.md',
    description: 'AWS tooling for cloud infrastructure, IAM, and Bedrock access.',
    safetyClass: 'credential_sensitive',
    requiresApprovalFor: ['deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'cloud'],
    verification: ['aws --version'],
    enabled: true,
  },
  {
    id: 'cli.azure',
    kind: 'cli',
    label: 'Azure CLI',
    source: 'operations/runbooks/azure.md',
    description: 'Azure tooling for cloud infrastructure and resource management.',
    safetyClass: 'credential_sensitive',
    requiresApprovalFor: ['deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'cloud'],
    verification: ['az --version'],
    enabled: true,
  },
  {
    id: 'cli.gcp',
    kind: 'cli',
    label: 'Google Cloud CLI',
    source: 'operations/runbooks/gcp.md',
    description: 'Google Cloud tooling for cloud projects, infrastructure, and services.',
    safetyClass: 'credential_sensitive',
    requiresApprovalFor: ['deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'cloud'],
    verification: ['gcloud --version'],
    enabled: true,
  },
  {
    id: 'cli.hetzner',
    kind: 'cli',
    label: 'Hetzner Cloud CLI',
    source: 'operations/runbooks/hetzner.md',
    description: 'Hetzner Cloud tooling for server and infrastructure lifecycle operations.',
    safetyClass: 'credential_sensitive',
    requiresApprovalFor: ['deploy', 'external_state', 'credential_sensitive'],
    preferredAiTaskTypes: ['infrastructure', 'cloud'],
    verification: ['hcloud --version'],
    enabled: true,
  },
  {
    id: 'cli.tailscale',
    kind: 'cli',
    label: 'Tailscale CLI',
    source: 'operations/runbooks/tailscale.md',
    description: 'Tailscale tooling for network inspection, device management, and connectivity checks.',
    safetyClass: 'external_state',
    requiresApprovalFor: ['external_state'],
    preferredAiTaskTypes: ['networking', 'connectivity', 'infrastructure'],
    verification: ['tailscale version'],
    enabled: true,
  },
  {
    id: 'cli.stripe',
    kind: 'cli',
    label: 'Stripe CLI',
    source: 'operations/runbooks/stripe-cli-and-probot.md',
    description: 'Stripe tooling for billing and payment-related operational work.',
    safetyClass: 'financial',
    requiresApprovalFor: ['financial', 'credential_sensitive', 'external_state'],
    preferredAiTaskTypes: ['billing', 'payments', 'financial'],
    verification: ['stripe version'],
    enabled: true,
  },
  {
    id: 'cli.n8n',
    kind: 'cli',
    label: 'n8n CLI',
    source: 'brain/ai/skills/custom/n8n/n8n-cli/SKILL.md',
    description: 'n8n tooling for workflow automation and orchestration.',
    safetyClass: 'external_state',
    requiresApprovalFor: ['external_state', 'deploy', 'credential_sensitive'],
    preferredAiTaskTypes: ['automation', 'workflow', 'infrastructure'],
    verification: ['n8n --help'],
    enabled: true,
  },
  {
    id: 'cli.github',
    kind: 'cli',
    label: 'GitHub CLI',
    source: 'operations/runbooks/github.md',
    description: 'GitHub tooling for repository and pull request operations.',
    safetyClass: 'repo_write',
    requiresApprovalFor: ['commit', 'push', 'repo_write'],
    preferredAiTaskTypes: ['code', 'repo_management'],
    verification: ['gh --version'],
    enabled: true,
  },
];

export function listAgentCliCapabilities(): AgentCapabilitySummary[] {
  return CLI_CAPABILITIES.map((capability) => ({
    ...capability,
    requiresApprovalFor: [...capability.requiresApprovalFor],
    preferredAiTaskTypes: [...capability.preferredAiTaskTypes],
    verification: [...capability.verification],
  }));
}
