import type { BrainCoreOrchestratorSummary } from '../types/api.js';

const ORCHESTRATORS: BrainCoreOrchestratorSummary[] = [
  {
    id: 'brain-core',
    name: 'Brain Core',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'primary',
    description: 'Central registry and orchestration service',
  },
  {
    id: 'brain-console',
    name: 'Brain Console',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'primary',
    description: 'Obsidian plugin for unified dashboard',
  },
  {
    id: 'mind-steward',
    name: 'Mind Steward',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'primary',
    description: 'AI model routing and cost optimization',
  },
  {
    id: 'probot-dashboard',
    name: 'ProBot Dashboard',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'warning',
    lifecycle: 'legacy',
    role: 'legacy',
    description: 'Legacy dashboard service',
  },
  {
    id: 'save-to-mind',
    name: 'Save to Mind',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'supporting',
    description: 'Capture and persist to Mind vault',
  },
  {
    id: 'scheduler',
    name: 'Scheduler',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'primary',
    description: 'Cron-based task scheduling',
  },
  {
    id: 'stb-pipeline',
    name: 'Says the Bible Pipeline',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'error',
    lifecycle: 'migrating',
    role: 'primary',
    description: 'Daily Bible content generation and publication',
  },
  {
    id: 'video-orchestrator',
    name: 'Video Orchestrator',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'warning',
    lifecycle: 'partial',
    role: 'primary',
    description: 'Multi-platform video production and posting',
  },
  {
    id: 'design-orchestrator',
    name: 'Design Orchestrator',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'supporting',
    description: 'Design system and UI component generation',
  },
  {
    id: 'code-orchestrator',
    name: 'Code Orchestrator',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'supporting',
    description: 'Code review, analysis, and refactoring',
  },
  {
    id: 'research-orchestrator',
    name: 'Research Orchestrator',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'supporting',
    description: 'Web research and information gathering',
  },
  {
    id: 'bible-research',
    name: 'Bible Research',
    status: 'placeholder',
    source: 'placeholder',
    actionsSupported: false,
    health: 'ok',
    lifecycle: 'operational',
    role: 'supporting',
    description: 'Scriptural content analysis and retrieval',
  },
];

export function listOrchestrators(): BrainCoreOrchestratorSummary[] {
  return ORCHESTRATORS;
}

export function getOrchestrator(id: string): BrainCoreOrchestratorSummary | undefined {
  return ORCHESTRATORS.find(o => o.id === id);
}
