import type {
  BrainCorePostOrchestratorContractsResponse,
  BrainCorePostOrchestratorIntegrationsResponse,
  BrainCorePostOrchestratorRecoveryResponse,
  BrainCorePostOrchestratorStatusResponse,
} from '../types/api.js';

const STATUS: BrainCorePostOrchestratorStatusResponse = {
  id: 'post-orchestrator',
  name: 'Post Orchestrator',
  status: 'partial',
  summary: 'Brain owns the canonical post orchestration surface in read-only P1.',
  phase: 'P1-read-only-status-scaffold',
  publishingEnabled: false,
  schedulingEnabled: false,
  executionEnabled: false,
  socialProofFlowLabel: 'Social Proof Asset Flow',
  growthOptimizationFlowLabel: 'Growth Optimization Flow',
  modules: [
    {
      id: 'event-ingestion',
      name: 'Event Ingestion',
      status: 'planned',
      summary: 'Canonical post event intake for Brain-owned orchestration.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['No live event ingestion path exposed in P1'],
      nextSafeStep: 'Define typed event fixture adapters before execution work.',
    },
    {
      id: 'post-draft-generation',
      name: 'Post Draft Generation',
      status: 'planned',
      summary: 'Draft synthesis and content shaping remain read-only in this phase.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Draft generation is not wired to a write-enabled workflow'],
      nextSafeStep: 'Add read-only draft contract fixtures.',
    },
    {
      id: 'approval-review',
      name: 'Approval Review',
      status: 'partial',
      summary: 'Brain approval infrastructure exists, but post execution remains disabled.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Approval review does not unlock publishing in P1'],
      nextSafeStep: 'Keep approvals read-only until a later phase.',
    },
    {
      id: 'scheduling-queue',
      name: 'Scheduling Queue',
      status: 'disabled',
      summary: 'Scheduling is visible but intentionally disabled.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Scheduling is disabled for P1'],
      nextSafeStep: 'Delay queue execution until policy and validation are ready.',
    },
    {
      id: 'publishing-adapter',
      name: 'Publishing Adapter',
      status: 'disabled',
      summary: 'Publishing execution is not exposed from Brain in this slice.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Publishing is disabled in P1'],
      nextSafeStep: 'Keep the adapter read-only until a future execution phase.',
    },
    {
      id: 'analytics-feedback',
      name: 'Analytics Feedback',
      status: 'planned',
      summary: 'Analytics interpretation is reserved for later feedback loops.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['No analytics feedback execution path in P1'],
      nextSafeStep: 'Add passive analytics summary contracts only.',
    },
    {
      id: 'x-post-flow',
      name: 'X Post Flow',
      status: 'planned',
      summary: 'X platform post flow remains a read-only planning surface.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the X post flow as a planning-only module.',
    },
    {
      id: 'github-post-flow',
      name: 'GitHub Post Flow',
      status: 'planned',
      summary: 'GitHub post flow captures release and milestone sharing intent.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the GitHub post flow as a planning-only module.',
    },
    {
      id: 'linkedin-post-flow',
      name: 'LinkedIn Post Flow',
      status: 'planned',
      summary: 'LinkedIn post flow captures professional content planning.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the LinkedIn post flow as a planning-only module.',
    },
    {
      id: 'facebook-post-flow',
      name: 'Facebook Post Flow',
      status: 'planned',
      summary: 'Facebook post flow captures broad social distribution planning.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the Facebook post flow as a planning-only module.',
    },
    {
      id: 'youtube-post-flow',
      name: 'YouTube Post Flow',
      status: 'planned',
      summary: 'YouTube post flow captures video distribution planning.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the YouTube post flow as a planning-only module.',
    },
    {
      id: 'blog-post-flow',
      name: 'Blog Post Flow',
      status: 'planned',
      summary: 'Blog post flow captures article publication planning.',
      owner: 'platform',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the blog post flow as a planning-only module.',
    },
    {
      id: 'product-milestone-post-flow',
      name: 'Product Milestone Post Flow',
      status: 'planned',
      summary: 'Product milestone post flow captures launch and milestone announcements.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the milestone post flow as a planning-only module.',
    },
    {
      id: 'release-announcement-post-flow',
      name: 'Release Announcement Post Flow',
      status: 'planned',
      summary: 'Release announcement post flow captures release note communication.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['Publishing is disabled'],
      nextSafeStep: 'Keep the release announcement post flow as a planning-only module.',
    },
    {
      id: 'social-proof-asset-flow',
      name: 'Social Proof Asset Flow',
      internalName: 'Proofly Asset Provider',
      legacySource: 'proofly',
      status: 'planned',
      summary: 'Legacy Proofly asset capability is represented as a neutral read-only flow.',
      owner: 'proofly',
      executionEnabled: false,
      blockers: ['Legacy asset system migration remains read-only'],
      nextSafeStep: 'Keep the social proof asset flow neutral and read-only.',
    },
    {
      id: 'growth-optimization-flow',
      name: 'Growth Optimization Flow',
      internalName: 'Xgrow Optimization Provider',
      legacySource: 'xgrow',
      status: 'planned',
      summary: 'Legacy Xgrow optimization capability is represented as a neutral read-only flow.',
      owner: 'xgrow',
      executionEnabled: false,
      blockers: ['Legacy growth system migration remains read-only'],
      nextSafeStep: 'Keep the growth optimization flow neutral and read-only.',
    },
    {
      id: 'recovery-audit',
      name: 'Recovery Audit',
      status: 'planned',
      summary: 'Recovery and blocker tracking remain visible and read-only.',
      owner: 'brain',
      executionEnabled: false,
      blockers: ['No post recovery automation exposed in P1'],
      nextSafeStep: 'Audit blockers after contracts are validated.',
    },
  ],
  nextSafeStep: 'Validate typed contracts and keep publishing disabled.',
  updatedAt: new Date().toISOString(),
};

const CONTRACTS: BrainCorePostOrchestratorContractsResponse = {
  contracts: [
    {
      id: 'PostEvent',
      name: 'Post Event',
      status: 'defined',
      version: 'p1',
      owner: 'brain',
      summary: 'Canonical event emitted into the Brain Post Orchestrator.',
      fields: ['id', 'source', 'eventType', 'occurredAt', 'payloadSummary', 'projectId', 'priority', 'suggestedPostTypes'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'PostDraft',
      name: 'Post Draft',
      status: 'defined',
      version: 'p1',
      owner: 'brain',
      summary: 'Read-only draft state synthesized before any approval.',
      fields: ['id', 'eventId', 'platform', 'format', 'copy', 'threadItems', 'assetRequests', 'optimizationRequests', 'status', 'approvalRequired', 'approvalId'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'ProoflyAssetRequest',
      name: 'Social Proof Asset Request',
      status: 'defined',
      version: 'p1',
      owner: 'proofly',
      summary: 'Typed request for social proof asset generation.',
      fields: ['id', 'projectId', 'assetType', 'templateId', 'data', 'brand', 'outputFormat'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'ProoflyAssetResult',
      name: 'Social Proof Asset Result',
      status: 'defined',
      version: 'p1',
      owner: 'proofly',
      summary: 'Typed response contract for social proof asset outputs.',
      fields: ['id', 'requestId', 'status', 'previewPath', 'assetPath', 'metadata'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'XgrowOptimizationRequest',
      name: 'Growth Optimization Request',
      status: 'defined',
      version: 'p1',
      owner: 'xgrow',
      summary: 'Typed request for growth hook, copy, and timing optimization.',
      fields: ['id', 'eventId', 'platform', 'draftId', 'signals', 'audience', 'constraints'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'XgrowOptimizationResult',
      name: 'Growth Optimization Result',
      status: 'defined',
      version: 'p1',
      owner: 'xgrow',
      summary: 'Typed response contract for growth optimization guidance.',
      fields: ['id', 'requestId', 'status', 'recommendedHook', 'recommendedCopy', 'timingRecommendation', 'viralityScore', 'riskNotes'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'PostScheduleItem',
      name: 'Post Schedule Item',
      status: 'defined',
      version: 'p1',
      owner: 'brain',
      summary: 'Canonical schedule record for future Brain-owned orchestration.',
      fields: ['id', 'draftId', 'scheduledAt', 'platform', 'approvalId', 'status'],
      implementedInBrain: true,
      implementedInProvider: false,
      executionEnabled: false,
    },
    {
      id: 'PostAnalyticsResult',
      name: 'Post Analytics Result',
      status: 'draft',
      version: 'p1',
      owner: 'brain',
      summary: 'Passive analytics feedback payload for later optimization loops.',
      fields: ['id', 'postId', 'impressions', 'clicks', 'engagementRate', 'notes'],
      implementedInBrain: false,
      implementedInProvider: false,
      executionEnabled: false,
    },
  ],
};

const INTEGRATIONS: BrainCorePostOrchestratorIntegrationsResponse = {
  integrations: [
    {
      id: 'proofly-social-proof-assets',
      provider: 'proofly',
      name: 'Social Proof Asset Flow',
      internalName: 'Proofly Social Proof Assets',
      legacySource: 'proofly',
      status: 'contract-defined',
      role: 'social proof asset flow',
      summary: 'Legacy Proofly supplies branded proof cards, templates, and preview/export assets.',
      contractIds: ['ProoflyAssetRequest', 'ProoflyAssetResult'],
      executionEnabled: false,
      publishingEnabled: false,
      schedulingEnabled: false,
      safety: {
        readsSecrets: false,
        usesCookies: false,
        usesPlaywright: false,
        writesExternalPlatform: false,
        writesToMind: false,
        requiresApproval: false,
      },
      blockers: ['Legacy asset system migration remains read-only'],
      nextSafeStep: 'Keep the social proof asset flow neutral and read-only.',
    },
    {
      id: 'xgrow-growth-optimization',
      provider: 'xgrow',
      name: 'Growth Optimization Flow',
      internalName: 'Xgrow Growth Optimization',
      legacySource: 'xgrow',
      status: 'contract-defined',
      role: 'growth optimization flow',
      summary: 'Legacy Xgrow provides copy hooks, timing, virality, segmentation, and engagement guidance.',
      contractIds: ['XgrowOptimizationRequest', 'XgrowOptimizationResult'],
      executionEnabled: false,
      publishingEnabled: false,
      schedulingEnabled: false,
      safety: {
        readsSecrets: false,
        usesCookies: true,
        usesPlaywright: true,
        writesExternalPlatform: false,
        writesToMind: false,
        requiresApproval: true,
      },
      blockers: ['Security review required before any Playwright posting exposure', 'No publish path is enabled in Brain P1'],
      nextSafeStep: 'Treat cookies and Playwright usage as risk metadata only.',
    },
    {
      id: 'brain-post-orchestrator-core',
      provider: 'brain',
      name: 'Brain Post Orchestrator Core',
      status: 'planned',
      role: 'canonical orchestration runtime',
      summary: 'Brain owns the read-only canonical post orchestration surface in P1.',
      contractIds: ['PostEvent', 'PostDraft', 'PostScheduleItem', 'PostAnalyticsResult'],
      executionEnabled: false,
      publishingEnabled: false,
      schedulingEnabled: false,
      safety: {
        readsSecrets: false,
        usesCookies: false,
        usesPlaywright: false,
        writesExternalPlatform: false,
        writesToMind: false,
        requiresApproval: true,
      },
      blockers: ['Publishing is disabled', 'Scheduling is disabled'],
      nextSafeStep: 'Validate typed fixtures and keep the runtime read-only.',
    },
  ],
};

const RECOVERY: BrainCorePostOrchestratorRecoveryResponse = {
  items: [
    {
      id: 'post-orchestrator-not-implemented',
      severity: 'warning',
      source: 'brain',
      title: 'Post Orchestrator is read-only scaffold only',
      summary: 'Canonical Brain orchestration exists as a status surface, not execution logic.',
      blocker: 'No execution path in P1',
      nextSafeStep: 'Keep the scaffold visible while contracts are validated.',
      canAutoFix: false,
      executionEnabled: false,
    },
    {
      id: 'social-proof-asset-flow-not-integrated',
      severity: 'warning',
      source: 'proofly',
      title: 'Social proof asset flow not integrated',
      summary: 'Legacy asset migration remains visible, but Brain does not execute against it in P1.',
      blocker: 'Legacy asset flow is contract-defined only',
      nextSafeStep: 'Preserve the social proof asset flow as read-only.',
      canAutoFix: false,
      executionEnabled: false,
    },
    {
      id: 'growth-optimization-flow-not-integrated',
      severity: 'warning',
      source: 'xgrow',
      title: 'Growth optimization flow not integrated',
      summary: 'Legacy growth migration remains visible, but Brain does not execute against it in P1.',
      blocker: 'Legacy growth flow is contract-defined only',
      nextSafeStep: 'Preserve the growth optimization flow as read-only.',
      canAutoFix: false,
      executionEnabled: false,
    },
    {
      id: 'publishing-disabled',
      severity: 'error',
      source: 'platform',
      title: 'Publishing disabled',
      summary: 'Publishing is intentionally disabled in Brain P1.',
      blocker: 'No post is scheduled or published from Brain in P1',
      nextSafeStep: 'Keep publishing disabled until a later execution phase.',
      canAutoFix: false,
      executionEnabled: false,
    },
    {
      id: 'growth-optimization-playwright-security-review-required',
      severity: 'error',
      source: 'xgrow',
      title: 'Growth optimization Playwright security review required',
      summary: 'Browser posting risk is metadata only and must be reviewed before exposure.',
      blocker: 'Playwright/cookie exposure needs security review',
      nextSafeStep: 'Require a security review before any posting path is exposed.',
      canAutoFix: false,
      executionEnabled: false,
    },
    {
      id: 'no-dual-run-validation-yet',
      severity: 'info',
      source: 'contract',
      title: 'No dual-run validation yet',
      summary: 'Brain and the legacy migration sources have not been validated in dual-run mode.',
      blocker: 'No dual-run evidence exists',
      nextSafeStep: 'Add fixture-backed validation before any future execution work.',
      canAutoFix: false,
      executionEnabled: false,
    },
  ],
};

export function readPostOrchestratorStatus(): BrainCorePostOrchestratorStatusResponse {
  return STATUS;
}

export function readPostOrchestratorContracts(): BrainCorePostOrchestratorContractsResponse {
  return CONTRACTS;
}

export function readPostOrchestratorIntegrations(): BrainCorePostOrchestratorIntegrationsResponse {
  return INTEGRATIONS;
}

export function readPostOrchestratorRecovery(): BrainCorePostOrchestratorRecoveryResponse {
  return RECOVERY;
}
