import type {
  BrainCoreProBotDashboardParityResponse,
  BrainCoreProBotDashboardParityTab,
} from '../types/api.js';

const tabs: BrainCoreProBotDashboardParityTab[] = [
  {
    id: 'overview',
    probotLabel: 'Overview',
    brainConsoleSection: 'overview',
    status: 'available',
    decision: 'keep',
    priority: 'high',
    brainCoreEndpoints: ['/status', '/capabilities', '/runtime/reports', '/scheduler/status', '/approvals'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Core health, scheduler, approvals, and runtime report summaries are already visible in Brain Console.'],
    nextSafeStep: 'Keep Overview as the primary landing section and add parity badges as migration evidence.',
  },
  {
    id: 'local-apps',
    probotLabel: 'Local Apps',
    brainConsoleSection: 'apps',
    status: 'available',
    decision: 'keep',
    priority: 'high',
    brainCoreEndpoints: ['/local-apps'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Brain Core exposes read-only local app status. Start/stop/restart remain disabled or approval-gated only.'],
    nextSafeStep: 'Compare ProBot app registry fields against Brain Core local-app summaries and add missing read-only metadata.',
  },
  {
    id: 'production-pipeline',
    probotLabel: 'Production Pipeline',
    brainConsoleSection: 'pipelines',
    status: 'partial',
    decision: 'redesign',
    priority: 'medium',
    brainCoreEndpoints: ['/pipelines', '/stb/status', '/video-orchestrator/status', '/stb-video-migration/status'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Says the Bible and Video Orchestrator are visible side-by-side through Brain Core, but ProBot-specific workflow queue parity still needs a read-only mapping pass.'],
    nextSafeStep: 'Add a read-only ProBot workflow queue summary if safe source data is available without exposing secrets or enabling execution.',
  },
  {
    id: 'video-orchestrator-studio',
    probotLabel: 'Video Orchestrator Studio',
    brainConsoleSection: 'pipelines',
    status: 'partial',
    decision: 'redesign',
    priority: 'high',
    brainCoreEndpoints: ['/video-orchestrator/status', '/video-orchestrator/controlled-execution-implementation-approval-packet-start-gate'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Credentials and OAuth flows must stay out of Brain Console. Brain Console should show account health and controlled-execution readiness only.'],
    nextSafeStep: 'Add read-only account health parity cards without tokens, secrets, OAuth state, or platform-write controls.',
  },
  {
    id: 'viral-flow',
    probotLabel: 'Viral Flow',
    brainConsoleSection: 'posts',
    status: 'partial',
    decision: 'redesign',
    priority: 'medium',
    brainCoreEndpoints: ['/post-orchestrator/status', '/post-orchestrator/overview', '/post-orchestrator/integrations', '/post-orchestrator/analytics'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Viral Flow is represented through Brain Post Orchestrator and should use flow names rather than legacy product names in the primary UI.'],
    nextSafeStep: 'Verify every ProBot Viral Flow card has a Brain Console Post Orchestrator equivalent or an explicit legacy-only decision.',
  },
  {
    id: 'stripe',
    probotLabel: 'Stripe',
    brainConsoleSection: 'none',
    status: 'legacy-only',
    decision: 'drop',
    priority: 'low',
    brainCoreEndpoints: [],
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Stripe billing is financial/admin data and remains intentionally out of Brain Console.'],
    nextSafeStep: 'Keep Stripe in ProBot/admin-only surfaces unless a separate explicit financial dashboard approval is given.',
  },
  {
    id: 'session-history',
    probotLabel: 'Session History',
    brainConsoleSection: 'overview',
    status: 'available',
    decision: 'keep',
    priority: 'high',
    brainCoreEndpoints: ['/sessions', '/repos', '/agent-runs', '/agent-events'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Recent sessions and agent activity are available through Brain Core and visible in Brain Console.'],
    nextSafeStep: 'Polish continuation UX in Brain Console after parity inventory is complete.',
  },
  {
    id: 'system-updates',
    probotLabel: 'System Updates',
    brainConsoleSection: 'recovery',
    status: 'planned',
    decision: 'later',
    priority: 'medium',
    brainCoreEndpoints: ['/recovery', '/execution/maintenance-previews'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    mutationControlsEnabled: false,
    sensitiveDataExposed: false,
    notes: ['Read-only maintenance and recovery views exist, but ProBot update workflow parity is not implemented yet.'],
    nextSafeStep: 'Design a read-only available-update summary before any approval-gated update action.',
  },
];

export function readProBotDashboardParity(): BrainCoreProBotDashboardParityResponse {
  const availableCount = tabs.filter(tab => tab.status === 'available').length;
  const partialCount = tabs.filter(tab => tab.status === 'partial').length;
  const plannedCount = tabs.filter(tab => tab.status === 'planned').length;
  const legacyOnlyCount = tabs.filter(tab => tab.status === 'legacy-only').length;
  const visibleCount = tabs.filter(tab => tab.visibleInBrainConsole).length;
  const workingCount = tabs.filter(tab => tab.workingInBrainConsole).length;
  const blockerCount = tabs.reduce((count, tab) => count + (tab.workingInBrainConsole ? 0 : 1), 0);

  return {
    id: 'probot-dashboard-parity',
    generatedAt: new Date().toISOString(),
    status: 'in-progress',
    summary: {
      totalTabs: tabs.length,
      availableCount,
      partialCount,
      plannedCount,
      legacyOnlyCount,
      visibleInBrainConsoleCount: visibleCount,
      workingInBrainConsoleCount: workingCount,
      blockerCount,
    },
    tabs,
    safety: {
      readOnly: true,
      exposesSecrets: false,
      exposesFinancialData: false,
      mutationControlsEnabled: false,
      directShellExecutionEnabled: false,
      approvalRequiredForFutureActions: true,
      writesToMind: false,
      writesFiles: false,
    },
    nextSafeStep: 'Implement ProBot dashboard parity cards in Brain Console, starting with read-only account health and workflow queue summaries.',
  };
}
