import type {
  BrainCoreProBotExternalAdminParityResponse,
  BrainCoreProBotParityFeature,
} from '../types/api.js';

const features: BrainCoreProBotParityFeature[] = [
  {
    id: 'dokploy-status',
    label: 'Dokploy',
    probotTab: 'Dokploy',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Infrastructure deployment tool; no safe read-only summary available.',
    nextSafeStep: 'Keep in ProBot admin-only surface until dedicated ops dashboard exists.',
  },
  {
    id: 'new-relic-status',
    label: 'New Relic',
    probotTab: 'New Relic',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'External monitoring platform; credentials required.',
    nextSafeStep: 'Keep in ProBot admin-only surface until authenticated read-only API exists.',
  },
  {
    id: 'analytics-umami',
    label: 'Analytics / Umami',
    probotTab: 'Analytics',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Analytics data; no safe aggregate endpoint.',
    nextSafeStep: 'Create read-only aggregate metrics endpoint if analytics visibility needed.',
  },
  {
    id: 'google-ads-status',
    label: 'Google Ads',
    probotTab: 'Google Ads',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Campaign/account/spend data; no safe exposure without financial/account PII.',
    nextSafeStep: 'Keep in ProBot admin-only unless explicit metadata-only dashboard approved.',
  },
  {
    id: 'stripe-status',
    label: 'Stripe',
    probotTab: 'Stripe',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Financial data: accounts, customers, charges, tokens; intentionally blocked.',
    nextSafeStep: 'Keep Stripe in ProBot/admin-only unless separate financial dashboard approved.',
  },
  {
    id: 'domains-status',
    label: 'Domains',
    probotTab: 'Domains',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Domain registrar credentials; no safe metadata.',
    nextSafeStep: 'Keep in ProBot admin-only unless DNS metadata endpoint created.',
  },
  {
    id: 'tunnels-status',
    label: 'Tunnels',
    probotTab: 'Tunnels',
    brainConsoleSection: 'none',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeDataAvailable: false,
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    relatedBrainCoreEndpoints: [],
    blockedReason: 'Network tunnel tokens/URLs; infrastructure credential.',
    nextSafeStep: 'Keep in ProBot admin-only unless tunnel status metadata available.',
  },
];

export function readProBotExternalAdminParity(): BrainCoreProBotExternalAdminParityResponse {
  const availableCount = features.filter(f => f.migrationStatus === 'available').length;
  const partialCount = features.filter(f => f.migrationStatus === 'partial').length;
  const missingCount = features.filter(f => f.migrationStatus === 'missing').length;
  const legacyOnlyCount = features.filter(f => f.migrationStatus === 'legacy-only').length;
  const blockedCount = features.filter(f => f.migrationStatus === 'blocked').length;
  const visibleCount = features.filter(f => f.visibleInBrainConsole).length;
  const workingCount = features.filter(f => f.workingInBrainConsole).length;

  return {
    id: 'probot-external-admin-parity',
    source: 'probot',
    target: 'brain-console',
    status: 'legacy-only',
    migrationStatus: 'legacy-only',
    visibleInBrainConsole: false,
    workingInBrainConsole: false,
    legacyOnly: true,
    featureCount: features.length,
    features,
    summary: {
      availableCount,
      partialCount,
      missingCount,
      legacyOnlyCount,
      blockedCount,
      visibleCount,
      workingCount,
    },
    blockers: [
      'All external integrations require credentials/tokens/financial data.',
      'No safe read-only endpoints available.',
      'These remain intentionally admin-only.',
    ],
    safety: {
      readOnly: true,
      exposesSecrets: false,
      exposesCredentials: false,
      exposesOAuth: false,
      exposesStripeFinancialData: false,
      exposesRawLogs: false,
      mutationControlsEnabled: false,
      shellExecutionEnabled: false,
      platformWritesEnabled: false,
      mindWritesEnabled: false,
      publishingEnabled: false,
      decommissionEnabled: false,
    },
    nextSafeStep: 'Keep all external integrations in ProBot admin-only surfaces. Create separate dashboards only with explicit approval.',
  };
}
