import type {
  BrainCoreProBotFeatureParityMatrixResponse,
  BrainCoreProBotFeatureParityRow,
} from '../types/api.js';

const rows: BrainCoreProBotFeatureParityRow[] = [
  {
    probotTab: 'Sessions',
    brainConsoleCard: 'Sessions & Continuations',
    parityStatus: 'covered',
    safeDataStatus: 'available',
    endpointRefs: ['/probot/sessions-parity'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    decommissionBlocker: false,
    nextSafeStep: 'Sessions fully migrated. Ready for ProBot dashboard deprecation.',
  },
  {
    probotTab: 'Dokploy',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'intentionally-hidden',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Keep in ProBot admin-only until safe ops dashboard exists.',
  },
  {
    probotTab: 'New Relic',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'intentionally-hidden',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Keep in ProBot admin-only until authenticated read-only API exists.',
  },
  {
    probotTab: 'Scheduler',
    brainConsoleCard: 'Scheduler',
    parityStatus: 'covered',
    safeDataStatus: 'available',
    endpointRefs: ['/probot/scheduler-parity'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    decommissionBlocker: false,
    nextSafeStep: 'Scheduler fully migrated. Ready for ProBot dashboard deprecation.',
  },
  {
    probotTab: 'Analytics / Umami',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'metadata-only',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Create aggregate metrics endpoint without user session data.',
  },
  {
    probotTab: 'Google Ads',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'intentionally-hidden',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Keep in ProBot admin-only. No safe account/spend exposure without approval.',
  },
  {
    probotTab: 'Stripe',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'intentionally-hidden',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Keep in ProBot admin-only. Financial data intentionally blocked.',
  },
  {
    probotTab: 'Domains',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'metadata-only',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Create DNS metadata endpoint (domain names, expiration dates).',
  },
  {
    probotTab: 'Tunnels',
    brainConsoleCard: 'External Integrations (Admin-only)',
    parityStatus: 'legacy-only',
    safeDataStatus: 'intentionally-hidden',
    endpointRefs: ['/probot/external-admin-parity', '/probot/external-admin-safe-metadata'],
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    decommissionBlocker: true,
    nextSafeStep: 'Keep in ProBot admin-only until tunnel status metadata available.',
  },
  {
    probotTab: 'Local Apps',
    brainConsoleCard: 'Local Apps',
    parityStatus: 'covered',
    safeDataStatus: 'available',
    endpointRefs: ['/probot/local-apps-parity'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    decommissionBlocker: false,
    nextSafeStep: 'Local Apps fully migrated. Ready for ProBot dashboard deprecation.',
  },
  {
    probotTab: 'Studio / Viral Flow / Video Orchestrator',
    brainConsoleCard: 'Studio (Video/Viral Flow)',
    parityStatus: 'partial',
    safeDataStatus: 'available',
    endpointRefs: ['/probot/studio-parity'],
    visibleInBrainConsole: true,
    workingInBrainConsole: true,
    decommissionBlocker: true,
    nextSafeStep: 'Video Orchestrator ready, Viral Flow redesign pending (use Brain Post Orchestrator).',
  },
];

export function readProBotFeatureParityMatrix(): BrainCoreProBotFeatureParityMatrixResponse {
  const coveredCount = rows.filter(r => r.parityStatus === 'covered').length;
  const partialCount = rows.filter(r => r.parityStatus === 'partial').length;
  const legacyOnlyCount = rows.filter(r => r.parityStatus === 'legacy-only').length;
  const missingCount = rows.filter(r => r.parityStatus === 'missing').length;
  const blockedCount = rows.filter(r => r.parityStatus === 'blocked').length;
  const decommissionBlockerCount = rows.filter(r => r.decommissionBlocker).length;

  return {
    id: 'probot-feature-parity-matrix',
    status: 'partial',
    source: 'probot',
    target: 'brain-console',
    tabCount: rows.length,
    coveredCount,
    partialCount,
    legacyOnlyCount,
    missingCount,
    blockedCount,
    decommissionReady: false,
    rows,
    blockers: [
      `${decommissionBlockerCount} tabs are decommission blockers (legacy-only or partial).`,
      'Stripe, Google Ads, and financial data intentionally excluded from Brain Console.',
      'External integrations require credentials or expose sensitive data.',
      'Viral Flow studio redesign pending.',
    ],
    safety: {
      readOnly: true,
      exposesSecrets: false,
      exposesCredentials: false,
      exposesOAuth: false,
      exposesStripeFinancialData: false,
      exposesGoogleAdsSpendData: false,
      exposesAccountIds: false,
      exposesRawLogs: false,
      mutationControlsEnabled: false,
      shellExecutionEnabled: false,
      platformWritesEnabled: false,
      mindWritesEnabled: false,
      publishingEnabled: false,
      decommissionEnabled: false,
    },
    nextSafeStep: 'ProBot cannot be decommissioned until all 11 tabs are covered, partial, or explicitly approved as legacy-only.',
  };
}
