import type {
  BrainCoreProBotExternalAdminSafeMetadataResponse,
  BrainCoreProBotExternalAdminIntegration,
} from '../types/api.js';

const integrations: BrainCoreProBotExternalAdminIntegration[] = [
  {
    id: 'dokploy-metadata',
    label: 'Dokploy',
    probotTab: 'Dokploy',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'API keys',
      'deployment secrets',
      'webhook tokens',
      'SSH credentials',
      'server credentials',
    ],
    blockedReason: 'Infrastructure deployment tool; no safe metadata endpoint.',
    nextSafeStep: 'Keep in ProBot admin-only until dedicated ops dashboard with safe metadata exists.',
  },
  {
    id: 'new-relic-metadata',
    label: 'New Relic',
    probotTab: 'New Relic',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'API keys',
      'account tokens',
      'authentication credentials',
      'raw telemetry data',
    ],
    blockedReason: 'External monitoring platform; credentials required for any access.',
    nextSafeStep: 'Keep in ProBot admin-only until authenticated read-only API exists.',
  },
  {
    id: 'analytics-umami-metadata',
    label: 'Analytics / Umami',
    probotTab: 'Analytics',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'metadata-only',
    migrationStatus: 'partial',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'raw event logs',
      'user session data',
      'personal analytics data',
      'API tokens',
    ],
    blockedReason: 'Analytics data; no safe aggregate endpoint without user identifiers.',
    nextSafeStep: 'Create aggregate metrics endpoint (visitor count, page views, top pages) without session data.',
  },
  {
    id: 'google-ads-metadata',
    label: 'Google Ads',
    probotTab: 'Google Ads',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'account IDs',
      'customer IDs',
      'spend data',
      'campaign performance data',
      'conversion data',
      'API tokens',
      'OAuth credentials',
    ],
    blockedReason: 'Campaign/account/spend data; no safe exposure without financial/account PII.',
    nextSafeStep: 'Keep in ProBot admin-only unless explicit metadata-only dashboard approved.',
  },
  {
    id: 'stripe-metadata',
    label: 'Stripe',
    probotTab: 'Stripe',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'account IDs',
      'customer IDs',
      'charges',
      'card tokens',
      'financial transactions',
      'API keys',
      'restricted API tokens',
    ],
    blockedReason: 'Financial data: accounts, customers, charges, tokens; intentionally blocked.',
    nextSafeStep: 'Keep Stripe in ProBot/admin-only unless separate financial dashboard approved.',
  },
  {
    id: 'domains-metadata',
    label: 'Domains',
    probotTab: 'Domains',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'metadata-only',
    migrationStatus: 'partial',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: ['domain names', 'expiration dates'],
    prohibitedFields: [
      'registrar credentials',
      'WHOIS data',
      'authentication codes',
      'transfer keys',
      'DNS records',
      'account IDs',
    ],
    blockedReason: 'Domain registrar credentials; no safe metadata available.',
    nextSafeStep: 'Keep in ProBot admin-only unless DNS metadata endpoint created.',
  },
  {
    id: 'tunnels-metadata',
    label: 'Tunnels',
    probotTab: 'Tunnels',
    brainConsoleSection: 'ProBot Migration / External Admin',
    migrationDecision: 'legacy-admin-only',
    migrationStatus: 'legacy-only',
    safeMetadataAvailable: false,
    visibleInBrainConsole: true,
    workingInBrainConsole: false,
    safeFields: [],
    prohibitedFields: [
      'tunnel tokens',
      'tunnel URLs',
      'authentication secrets',
      'connection strings',
      'infrastructure credentials',
    ],
    blockedReason: 'Network tunnel tokens/URLs; infrastructure credential.',
    nextSafeStep: 'Keep in ProBot admin-only unless tunnel status metadata available.',
  },
];

export function readProBotExternalAdminSafeMetadata(): BrainCoreProBotExternalAdminSafeMetadataResponse {
  const safeMetadataAvailableCount = integrations.filter(i => i.safeMetadataAvailable).length;
  const metadataOnlyCount = integrations.filter(i => i.migrationDecision === 'metadata-only').length;
  const legacyOnlyCount = integrations.filter(i => i.migrationDecision === 'legacy-admin-only').length;

  return {
    id: 'probot-external-admin-safe-metadata',
    status: 'partial',
    source: 'probot',
    target: 'brain-console',
    integrationCount: integrations.length,
    safeMetadataAvailableCount,
    metadataOnlyCount,
    legacyOnlyCount,
    integrations,
    safety: {
      readOnly: true,
      metadataOnly: true,
      exposesSecrets: false,
      exposesCredentials: false,
      exposesOAuth: false,
      exposesStripeFinancialData: false,
      exposesGoogleAdsSpendData: false,
      exposesAccountIds: false,
      exposesRawLogs: false,
      mutationControlsEnabled: false,
      shellExecutionEnabled: false,
      platformWritesEnabled: false,
      mindWritesEnabled: false,
      publishingEnabled: false,
      decommissionEnabled: false,
    },
    blockers: [
      'All external integrations require credentials or expose sensitive data.',
      'Stripe and Google Ads: financial/account data intentionally hidden.',
      'Domains and Tunnels: registration/connection secrets unavailable.',
      'New Relic and Dokploy: credential-dependent access only.',
      'Analytics: no user-identification-free aggregation available.',
    ],
    nextSafeStep: 'Keep all external integrations in ProBot admin-only until safe metadata endpoints created.',
  };
}
