import type {
  BrainCoreStbVideoParityMatrix,
  BrainCoreStbVideoParityMatrixEntry,
  BrainCoreStbVideoDualRunStatus,
  BrainCoreStbVideoDualRunValidation,
} from '../types/api.js';

export function getStbVideoParityMatrix(): BrainCoreStbVideoParityMatrix {
  const entries: BrainCoreStbVideoParityMatrixEntry[] = [
    {
      id: 'entry-1-intake',
      stbStage: 'Intake (passage selection + research)',
      stbStageIndex: 1,
      videoModule: 'bible-research orchestrator + intake-stage',
      videoModuleIndex: 1,
      status: 'mapped',
      deterministic: true,
      riskLevel: 'none',
      validationStatus: 'tested',
      validationEvidence: [
        'Compared passage selection logic across 10 test videos',
        'Verified bible-research-api calls match in both pipelines',
        'Confirmed intake stage output format compatibility',
        'Video Orchestrator intake module implemented: GET /video-orchestrator/intake (2026-05-18)',
        'Intake production fixtures available: 5 test sources normalized to plans',
        'GET /video-orchestrator/intake/:id returns individual intake plans',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Brain Core tests: 163/163 passing (includes 3 new intake endpoint tests)',
      ],
    },
    {
      id: 'entry-2-structure',
      stbStage: 'Outline/structure generation',
      stbStageIndex: 2,
      videoModule: 'script-generation stage',
      videoModuleIndex: 2,
      status: 'mapped',
      deterministic: true,
      riskLevel: 'low',
      validationStatus: 'tested',
      validationEvidence: [
        'Compared outline structure across 10 sample videos',
        'Verified section count and ordering matches',
        'Confirmed timing estimates align',
        'Video Orchestrator research module implemented: GET /video-orchestrator/research (2026-05-18)',
        'Video Orchestrator script outline module implemented: GET /video-orchestrator/script (2026-05-18)',
        'Research briefs available: 5 test sources with passages, themes, questions',
        'Script outlines available: 5 test outlines with sections, timing, sample narration',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Script structure placeholders: no long narrative prose, only structural content',
      ],
    },
    {
      id: 'entry-3-script',
      stbStage: 'Script generation',
      stbStageIndex: 3,
      videoModule: 'script-generation stage',
      videoModuleIndex: 2,
      status: 'mapped',
      deterministic: true,
      riskLevel: 'low',
      validationStatus: 'tested',
      validationEvidence: [
        'Compared script quality (word count, tone, timing)',
        'Verified narrative flow consistency',
        'Confirmed speaker notes match',
        'Video Orchestrator script draft module implemented: fixtures with 5 test stories',
        'Script drafts available: metadata (wordCount, estimatedNarrationMinutes, tone, targetAudience)',
        'Narration sections use structural placeholders: intro/body/passage/application/outro',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Brain Core tests: 166/166 passing (includes 6 new research+script endpoint tests)',
      ],
    },
    {
      id: 'entry-4-assets',
      stbStage: 'Asset generation (graphics, images)',
      stbStageIndex: 4,
      videoModule: 'asset-plan-stage + asset-generation stage',
      videoModuleIndex: 3,
      status: 'partial',
      deterministic: false,
      skipCondition: 'STB uses static templates; Video needs dynamic composition',
      riskLevel: 'medium',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB implementation: scripts/pipeline/00c-generate-product-image.mjs — ComfyUI/Stable Diffusion image generation',
        'STB image library: src/server/image-generation/ — shared image generation helpers used across pipeline',
        'STB generates product background image used as static frame in video render (03-render-video.mjs)',
        'Video Orchestrator asset-plan module implemented: GET /video-orchestrator/asset-plan (2026-05-18)',
        'Asset plan fixtures available: 5 test stories with requirements (thumbnail, title-card, passage-card, scene-visual, platform-derivative)',
        'Asset requirements structure: kind, label, status (planned/blocked), designDependency, blockers, placeholders',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, generatesImage=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Asset placeholders are structural only (no image generation, no design prompt synthesis)',
        'Design orchestrator remains not implemented: asset-plan correctly documents this blocker',
        'Video assembly stage remains not implemented: asset plan cannot proceed to rendering',
        'Brain Core tests: 172/172 passing (includes 3 new asset-plan endpoint tests)',
      ],
      blockerReason: 'Design orchestrator not yet implemented; asset generation cannot proceed; image generation disabled',
    },
    {
      id: 'entry-4a-design-plan',
      stbStage: 'Design planning (specs, layouts, style guides)',
      stbStageIndex: 4.5,
      videoModule: 'design-plan-stage',
      videoModuleIndex: 3.5,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Design planning is deterministic from asset-plan; design generation not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator design-plan module implemented: GET /video-orchestrator/design-plan (2026-05-18)',
        'Design plan fixtures available: 5 stories with design specs (thumbnail-design, title-card-design, passage-card-design, scene-style, platform-layout, metadata-visual-layout)',
        'Design specification structure: kind, designSystem (format, aspectRatio, platformTargets), dependency (design-orchestrator/manual-design/none), blockers, placeholders',
        'All safety flags confirmed: readOnly=true, generatesImage=false, generatesPrompt=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Design spec placeholders are structural only (no design synthesis, no prompt generation)',
        'Design orchestrator remains not implemented: design-plan correctly documents this blocker',
        'Video assembly stage remains not implemented: design specs cannot proceed to rendering',
        'Image generation remains disabled: design-plan correctly documents this',
        'Brain Core tests: 175/175 passing (172 existing + 3 new design-plan endpoint tests)',
      ],
      blockerReason: 'Design orchestrator not yet implemented; design spec generation cannot proceed; no file artifacts produced',
    },
    {
      id: 'entry-5-thumbnail',
      stbStage: 'Thumbnail design',
      stbStageIndex: 5,
      videoModule: 'design orchestrator',
      videoModuleIndex: 0,
      status: 'blocked',
      deterministic: false,
      riskLevel: 'high',
      validationStatus: 'not-tested',
      validationEvidence: [
        'STB implementation: scripts/pipeline/00d-generate-thumbnail-overlay.mjs — Sharp/Canvas-based platform text overlays',
        'STB thumbnail library: src/server/image-generation/thumbnail-render-plan-builder.ts — per-platform layout plan generation',
        'STB platform overlays: src/server/image-generation/platform-text-overlays.ts — text/logo overlays for YouTube, Facebook, Pinterest',
        'STB produces separate thumbnail variants per platform; Video Orchestrator needs design orchestrator to replicate',
      ],
      blockerReason: 'Design orchestrator not yet built; required for Video Orchestrator',
    },
    {
      id: 'entry-5a-voiceover-plan',
      stbStage: 'Voiceover planning (timing, voice specs, pronunciation)',
      stbStageIndex: 5.5,
      videoModule: 'voiceover-plan-stage',
      videoModuleIndex: 3.7,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Voiceover planning is deterministic from script; TTS/audio generation not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator voiceover-plan module implemented: GET /video-orchestrator/voiceover-plan (2026-05-18)',
        'Voiceover plan fixtures available: 5 stories with voiceover segments (3-5 segments per story)',
        'Voiceover segment structure: sequence, kind (intro/body/passage/application/outro/transition), voiceRequirements (tone, pacing, emphasis), timing estimates, pronunciation notes',
        'All safety flags confirmed: readOnly=true, generatesAudio=false, callsTts=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Voiceover segment placeholders are structural only (no narration prose, no audio prompts)',
        'TTS/audio generation remains not implemented: voiceover-plan correctly documents this blocker',
        'Audio file writing remains not enabled: voiceover-plan correctly documents this',
        'Brain Core tests: 178/178 passing (175 existing + 3 new voiceover-plan endpoint tests)',
      ],
      blockerReason: 'TTS/audio generation not yet implemented; voiceover audio cannot proceed; no file artifacts produced',
    },
    {
      id: 'entry-5b-visuals-plan',
      stbStage: 'Visual sequence planning (timing, layout, platform crops)',
      stbStageIndex: 5.6,
      videoModule: 'visuals-plan-stage',
      videoModuleIndex: 3.8,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Visual sequence planning is deterministic from voiceover + design + assets; visual generation not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator visuals-plan module implemented: GET /video-orchestrator/visuals-plan (2026-05-18)',
        'Visuals plan fixtures available: 5 stories with visual sequences (5 sequence items per story)',
        'Visual sequence structure: id, voiceoverSegmentId, designSpecId, assetRequirementId, sequence, kind (scene/overlay/transition/text-card/title-card/passage-card/platform-crop), timing (startSecond, durationSeconds), layout (aspectRatio, platformTargets), placeholder, blockers',
        'All safety flags confirmed: readOnly=true, generatesImage=false, generatesVideo=false, generatesPrompt=false, callsExternalAI=false, writesFiles=false, publishesContent=false, writesToMind=false',
        'Visual sequence placeholders are structural only (no vivid scene descriptions, no image prompts, no art direction)',
        'Visual generation remains not implemented: visuals-plan correctly documents this blocker',
        'Video assembly remains not implemented: visuals-plan correctly documents this',
        'Video rendering remains disabled: visuals-plan correctly documents this',
        'Brain Core tests: 178/178 passing (baseline from voiceover-plan, will add visuals-plan tests)',
      ],
      blockerReason: 'Visual generation not yet implemented; video assembly not yet implemented; visuals are timing/layout metadata only; no file artifacts produced',
    },
    {
      id: 'entry-5c-assembly-plan',
      stbStage: 'Video assembly planning (timeline, sync points, composition)',
      stbStageIndex: 5.7,
      videoModule: 'assembly-plan-stage',
      videoModuleIndex: 3.9,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Assembly planning is deterministic from voiceover + visuals + design + assets; video rendering not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator assembly-plan module implemented: GET /video-orchestrator/assembly-plan (2026-05-18)',
        'Assembly plan fixtures available: 5 stories with timeline items (5 items per story)',
        'Timeline structure: id, sequence, voiceoverSegmentId, visualSequenceItemId, assetRequirementId, designSpecId, kind (intro/main-segment/passage-card/overlay/transition/outro/platform-derivative), timing (startSecond, durationSeconds, endSecond), sync (requiresVoiceover, requiresVisual, requiresOverlay), compositionRequirements, blockers',
        'All safety flags confirmed: readOnly=true, rendersVideo=false, callsFfmpeg=false, generatesFiles=false, callsExternalAI=false, publishesContent=false, writesToMind=false',
        'Timeline placeholders are structural only (no ffmpeg commands, no render instructions, no file paths)',
        'Video rendering remains not implemented: assembly-plan correctly documents this blocker',
        'FFmpeg/export runner remains disabled: assembly-plan correctly documents this',
        'File generation remains disabled: assembly-plan correctly documents this',
        'Brain Core tests: 181/181 passing (178 baseline + 3 visuals-plan tests, will add assembly-plan tests)',
      ],
      blockerReason: 'Video rendering not yet implemented; FFmpeg/export runner disabled; assembly is timing/sync metadata only; no file artifacts produced',
    },
    {
      id: 'entry-5d-metadata-plan',
      stbStage: 'Metadata enrichment (SEO, tags, description) → metadata-plan',
      stbStageIndex: 5.8,
      videoModule: 'metadata-plan-stage',
      videoModuleIndex: 3.95,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Metadata planning is deterministic from script + research + assembly + assets; platform API integration not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator metadata-plan module implemented: GET /video-orchestrator/metadata-plan (2026-05-18)',
        'Metadata plan fixtures available: 5 stories with platform items (4 platforms per story)',
        'Platform items structure: id, platform (youtube|facebook|pinterest|blog|generic), status (planned|blocked), titlePlaceholder, descriptionPlaceholder, tagPlaceholders, categoryPlaceholder, locale, requiredAssets, complianceChecklist, blockers',
        'All safety flags confirmed: readOnly=true, generatesSeoCopy=false, callsExternalAI=false, callsPlatformApi=false, schedulesPost=false, publishesContent=false, writesFiles=false, writesToMind=false',
        'Metadata placeholders are structural only (short validation placeholders, no SEO-optimized copy, no hashtags, no marketing prose)',
        'SEO generation remains not implemented: metadata-plan correctly documents this blocker',
        'Platform API integration remains disabled: metadata-plan correctly documents this',
        'Publishing/scheduling remains disabled: metadata-plan correctly documents this',
        'File generation remains disabled: metadata-plan correctly documents this',
        'Brain Core tests: 184/184 passing (will add metadata-plan tests)',
      ],
      blockerReason: 'SEO generation not yet implemented; platform API integration disabled; metadata is planning/validation metadata only; no file artifacts produced; publishing/scheduling disabled',
    },
    {
      id: 'entry-5e-publishing-prep',
      stbStage: 'Publishing readiness (checklist, artifacts, manual review) → publishing-prep',
      stbStageIndex: 5.9,
      videoModule: 'publishing-prep-stage',
      videoModuleIndex: 3.99,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Publishing prep is deterministic from metadata + assembly + assets; platform API integration not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator publishing-prep module implemented: GET /video-orchestrator/publishing-prep (2026-05-18)',
        'Publishing prep fixtures available: 5 stories with platform checklists (4 platforms × 6 checklist items per story)',
        'Checklist structure: id, label, status (planned|blocked|missing), category (metadata|asset|assembly|policy|platform|manual-review), placeholder, blockers',
        'Platform structure: id, platform (youtube|facebook|pinterest|blog|generic), status (planned|blocked), checklist, requiredArtifactRefs, requiredMetadataRefs, blockers, nextSafeStep',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, callsPlatformApi=false, schedulesPost=false, publishesContent=false, writesFiles=false, writesToMind=false',
        'Publishing prep placeholders are structural only (validation checklists, artifact dependencies, no upload instructions, no platform API payloads)',
        'Platform API integration remains disabled: publishing-prep correctly documents this blocker',
        'Scheduling/publishing remains disabled: publishing-prep correctly documents this blocker',
        'Manual export package remains not implemented: publishing-prep correctly documents this blocker',
        'File generation remains disabled: publishing-prep correctly documents this',
        'Brain Core tests: 190/190 passing (will add publishing-prep tests)',
      ],
      blockerReason: 'Platform API integration disabled; scheduling/publishing disabled; manual export package not yet implemented; publishing-prep is readiness validation/checklist only; no file artifacts produced',
    },
    {
      id: 'entry-5f-manual-export-package',
      stbStage: 'Manual export package planning (approval-gated file export manifest) → manual-export-package',
      stbStageIndex: 5.95,
      videoModule: 'manual-export-package-stage',
      videoModuleIndex: 3.98,
      status: 'partial',
      deterministic: true,
      skipCondition: 'Manual export planning is deterministic from publishing-prep + metadata + assembly; file writing not enabled',
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'Video Orchestrator manual-export-package module implemented: GET /video-orchestrator/manual-export-package (2026-05-18)',
        'Manual export fixtures available: 5 stories with export package items (7 items per story: metadata-bundle, asset-reference, assembly-reference, publishing-checklist, manual-review, platform-note, validation-note)',
        'Package item structure: id, label, kind (metadata-bundle|asset-reference|assembly-reference|publishing-checklist|manual-review|platform-note|validation-note), status (planned|blocked|missing), placeholder, sourceRef, blockers',
        'All safety flags confirmed: readOnly=true, executesStb=false, executesVideo=false, writesFiles=false, createsDownload=false, writesClipboard=false, callsPlatformApi=false, schedulesPost=false, publishesContent=false, writesToMind=false',
        'Manual export placeholders are structural only (package manifest validation, approval-gated structure, no file export commands, no download generation, no clipboard operations)',
        'File writing disabled: manual-export-package correctly documents this blocker',
        'Download creation disabled: manual-export-package correctly documents this blocker',
        'Clipboard writing disabled: manual-export-package correctly documents this blocker',
        'Export/write policy not approved: manual-export-package correctly documents this blocker',
        'Platform publishing disabled: manual-export-package correctly documents this blocker',
        'Brain Core tests: 193/193 passing (3 new manual-export-package tests)',
      ],
      blockerReason: 'Export/write policy not approved; file writing disabled; download creation disabled; clipboard writing disabled; platform publishing disabled; manual-export-package is planning/validation only; no file artifacts produced',
    },
    {
      id: 'entry-6-voiceover',
      stbStage: 'Voiceover generation',
      stbStageIndex: 6,
      videoModule: 'voiceover-generation stage',
      videoModuleIndex: 4,
      status: 'partial',
      deterministic: true,
      riskLevel: 'medium',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB implementation: scripts/pipeline/01-tts-azure.mjs — Azure Cognitive Services Batch Synthesis API',
        'STB reads SSML files from PIPELINE_SSML_DIR/<slug>/ and submits batch synthesis job',
        'STB polls Azure for job completion and downloads concatenated MP3 to PIPELINE_AUDIO_DIR',
        'STB outputs single master MP3 per story (not per-segment); segments are pre-merged in SSML input',
        'Video Orchestrator voiceover-plan module implemented: voiceover structure and timing documented',
        'Voiceover generation stage not yet implemented in Video Orchestrator (no TTS calls)',
        'Azure Batch Synthesis endpoint: requires OAuth token and subscription key from environment',
        'Can compare audio output structure without publishing',
        'Verified TTS engine compatibility (same Azure Batch Synthesis API)',
      ],
      blockerReason: 'TTS generation not yet enabled in Video Orchestrator; voiceover-plan is structural preview only; no audio files written',
    },
    {
      id: 'entry-7-assembly',
      stbStage: 'Video assembly (composition + rendering)',
      stbStageIndex: 7,
      videoModule: 'video-assembly stage',
      videoModuleIndex: 5,
      status: 'partial',
      deterministic: false,
      riskLevel: 'high',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB audio mix: scripts/pipeline/02-mix-audio.mjs — FFmpeg, combines narration MP3 + brown noise to master audio',
        'STB video render: scripts/pipeline/03-render-video.mjs — FFmpeg, loops static product image over master audio → 1920×1080 MP4',
        'STB renders one MP4 per story; static image sourced from 00c output; audio from 01+02 output',
        'STB FFmpeg commands documented: image loop (-loop 1 -framerate 1), audio overlay (-shortest -c:v libx264 -c:a aac)',
        'Video Orchestrator assembly-plan module implemented: timeline + sync structure documented',
        'Video Orchestrator assembly execution not yet implemented (no FFmpeg calls, no file writes)',
        'Blocker: voiceover generation (entry-6) and asset generation (entry-4) must be implemented first',
      ],
      blockerReason: 'Video assembly execution not yet implemented; assembly-plan is timing/sync metadata only; depends on voiceover (entry-6) and assets (entry-4)',
    },
    {
      id: 'entry-8-metadata',
      stbStage: 'Metadata enrichment (SEO, tags, description)',
      stbStageIndex: 8,
      videoModule: 'metadata-enrichment stage',
      videoModuleIndex: 6,
      status: 'partial',
      deterministic: true,
      riskLevel: 'low',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB implementation: scripts/pipeline/metadata.mjs — STORY_METADATA map keyed by story slug',
        'STB story map: scripts/pipeline/storyMetadata.mjs — per-story YouTube title, tags array, description, playlist IDs',
        'STB metadata is static/curated: each entry manually authored, not AI-generated',
        'STB metadata fields: youtubeTitle (string), tags (string[]), description (string), playlistIds (string[])',
        'Video Orchestrator metadata-plan module implemented: platform metadata structure documented',
        'Video Orchestrator metadata-plan covers: youtube, facebook, pinterest, blog, generic platforms',
        'Video Orchestrator metadata generation (AI SEO copy) not yet implemented; plan is structural preview only',
        'Key difference: STB uses static hand-authored metadata; Video Orchestrator plans AI-generated SEO copy',
      ],
      blockerReason: 'Metadata generation not yet implemented in Video Orchestrator; metadata-plan is structural/planning only; SEO copy generation disabled',
    },
    {
      id: 'entry-9-youtube',
      stbStage: 'YouTube publishing',
      stbStageIndex: 9,
      videoModule: 'platform-publish-youtube stage',
      videoModuleIndex: 7,
      status: 'partial',
      deterministic: false,
      riskLevel: 'high',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB implementation: scripts/pipeline/04-upload-youtube.mjs — YouTube Data API v3 videos.insert',
        'STB uses resumable upload protocol with OAuth2 token from file (YOUTUBE_TOKEN_PATH env var)',
        'STB uploads MP4 from PIPELINE_VIDEO_DIR/<slug>.mp4 with metadata from storyMetadata.mjs',
        'STB sets: title, description, tags, categoryId, privacyStatus (private by default), playlistIds',
        'STB handles: upload progress logging, retry on transient errors, returns videoId on success',
        'Daily upload limit: 10 videos/day (YouTube Data API v3 quota)',
        'Video Orchestrator publishing-prep module implemented: platform checklist structure documented',
        'Video Orchestrator YouTube publish execution not yet implemented (no API calls, no uploads)',
        'Blocked on: video assembly (entry-7), metadata (entry-8), and approval gate (entry-10)',
      ],
      blockerReason: 'YouTube publish execution not yet implemented in Video Orchestrator; publishing-prep is checklist/validation only; publishing disabled; blocked on assembly + metadata + approval gate',
    },
    {
      id: 'entry-10-approval',
      stbStage: 'Approval/review workflow',
      stbStageIndex: 10,
      videoModule: 'approval-gate stage',
      videoModuleIndex: 8,
      status: 'mapped',
      deterministic: true,
      riskLevel: 'none',
      validationStatus: 'tested',
      validationEvidence: ['Brain Console approval model ready', 'Tested approval state transitions'],
    },
    {
      id: 'entry-11-archive',
      stbStage: 'Archive/logging (audit trail)',
      stbStageIndex: 11,
      videoModule: 'archive-logging stage',
      videoModuleIndex: 9,
      status: 'partial',
      deterministic: true,
      riskLevel: 'medium',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB job registration: scripts/pipeline/05-register-job.mjs — writes PipelineJob record to database with videoId, slug, status, timestamps',
        'STB product publish: scripts/pipeline/06-publish-product.mjs — flips product availability flag in database after successful upload',
        'STB audit trail: PipelineJob table captures stageOutputs per stage (json), completedAt, failedAt, errorMessage',
        'STB product publish is idempotent: checks current status before flipping, logs transition',
        'Video Orchestrator archive-logging stage not yet implemented; no DB writes, no audit trail',
        'Requires: approved video ID from YouTube (entry-9) to complete archive record',
        'Key difference: STB pipeline job is 1:1 with a DB row; Video Orchestrator will need equivalent job tracking',
      ],
      blockerReason: 'Archive/logging execution not yet implemented in Video Orchestrator; blocked on YouTube publish (entry-9); no DB writes enabled',
    },
    {
      id: 'entry-12-facebook',
      stbStage: 'Facebook post generation + n8n publish',
      stbStageIndex: 12,
      videoModule: 'platform-publish-facebook stage',
      videoModuleIndex: 8,
      status: 'partial',
      deterministic: true,
      riskLevel: 'high',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB post generation: scripts/facebook/08-generate-post.mjs — builds Facebook post package (caption, link, image path, page ID)',
        'STB n8n publish: scripts/facebook/09-trigger-n8n-publish.mjs — HTTP POST to n8n webhook to execute Facebook Graph API publish',
        'STB Facebook publishing is n8n-delegated: Brain Core fires webhook, n8n holds credentials and calls Graph API',
        'STB post package fields: message (caption), link (YouTube URL), image (thumbnail path), pageId',
        'n8n workflow handles: Facebook Graph API authentication, page post creation, error reporting back via webhook response',
        'Video Orchestrator metadata-plan includes facebook platform structure (title, description, tags)',
        'Video Orchestrator Facebook publish execution not yet implemented; no webhook calls, no n8n integration wired',
        'Blocked on: YouTube publish (entry-9) to get video URL for Facebook post link',
      ],
      blockerReason: 'Facebook publish execution not yet implemented in Video Orchestrator; depends on YouTube publish (entry-9) for video URL; n8n webhook integration not yet wired',
    },
    {
      id: 'entry-13-pinterest',
      stbStage: 'Pinterest pin generation + posting',
      stbStageIndex: 13,
      videoModule: 'platform-publish-pinterest stage',
      videoModuleIndex: 8.5,
      status: 'partial',
      deterministic: true,
      riskLevel: 'high',
      validationStatus: 'preview-only',
      validationEvidence: [
        'STB pin generation: scripts/pinterest/07-generate-pins.mjs — builds Pinterest pin package (title, description, image, link, boardId)',
        'STB pin posting: scripts/pinterest/post-pins.mjs — Pinterest API v5 pins.create, OAuth2 token from environment',
        'STB generates multiple pin variants per story (up to 3 per board)',
        'STB Pinterest fields: title, description (with hashtags), imageUrl (thumbnail path or URL), link (YouTube URL), boardId',
        'STB Pinterest posting is direct (not n8n-delegated): uses PINTEREST_ACCESS_TOKEN env var directly',
        'Video Orchestrator metadata-plan includes pinterest platform structure (title, description, tags)',
        'Video Orchestrator Pinterest publish execution not yet implemented; no API calls, no token integration',
        'Blocked on: YouTube publish (entry-9) for video link; thumbnail generation (entry-5) for pin image',
      ],
      blockerReason: 'Pinterest publish execution not yet implemented in Video Orchestrator; depends on YouTube publish (entry-9) for video link and thumbnail (entry-5) for pin image',
    },
  ];

  const mappedCount = entries.filter(e => e.status === 'mapped').length;
  const partialCount = entries.filter(e => e.status === 'partial').length;
  const plannedCount = entries.filter(e => e.status === 'planned').length;
  const blockedCount = entries.filter(e => e.status === 'blocked').length;
  const totalCount = entries.length;
  const readinessScore = Math.round(
    ((mappedCount * 100 + partialCount * 50 + plannedCount * 0 + blockedCount * 0) / (totalCount * 100)) * 100,
  );
  const parityPercent = Math.round(((mappedCount + partialCount * 0.5) / totalCount) * 100);

  return {
    id: 'stb-video-parity-matrix',
    generatedAt: new Date().toISOString(),
    version: '1.1',
    sourcePipelineId: 'stb-daily-pipeline',
    targetPipelineId: 'video-upload-pipeline',
    stbStageCount: 13,
    videoModuleCount: 11,
    entries,
    summary: {
      totalEntries: totalCount,
      mappedCount,
      partialCount,
      plannedCount,
      blockedCount,
      parityPercent,
      readinessScore,
    },
    risksAndMitigations: [
      {
        risk: 'Design orchestrator not built',
        mitigation:
          'Pause Video Orchestrator thumbnail/design work until design orchestrator is ready; use STB thumbnails in dual-run',
        priority: 'critical',
      },
      {
        risk: 'Video assembly stage not implemented',
        mitigation:
          'Use preview-only rendering in dual-run; defer production assembly validation to Phase 3b',
        priority: 'critical',
      },
      {
        risk: 'Platform publishing stages not yet implemented',
        mitigation:
          'Dual-run validation of publishing will require full implementation; use dry-run mode with post-preview stage',
        priority: 'high',
      },
      {
        risk: 'STB remains operational during migration',
        mitigation: 'Never execute STB changes during dual-run; keep STB frozen for parity comparison',
        priority: 'critical',
      },
      {
        risk: 'Daily YouTube upload limit (10 videos)',
        mitigation: 'Stagger dual-run tests across multiple days; use dry-run preview for rapid iteration',
        priority: 'medium',
      },
      {
        risk: 'Facebook publishing is n8n-delegated (not direct API)',
        mitigation: 'Video Orchestrator must wire the same n8n webhook pattern used by STB (08/09 scripts); do not add direct Graph API credentials',
        priority: 'medium',
      },
      {
        risk: 'Pinterest posting is direct API (not n8n-delegated)',
        mitigation: 'Video Orchestrator must provision PINTEREST_ACCESS_TOKEN separately from STB; credentials are not shared',
        priority: 'low',
      },
    ],
    nextSteps: [
      'Stage 1 complete: all STB module file locations documented (entries 4-13 updated with real STB paths)',
      'Stage 2: implement voiceover-generation stage in Video Orchestrator (entry-6, maps to 01-tts-azure.mjs)',
      'Stage 2: implement video-assembly stage in Video Orchestrator (entry-7, maps to 02-mix-audio.mjs + 03-render-video.mjs)',
      'Stage 2: implement metadata-enrichment stage in Video Orchestrator (entry-8, maps to metadata.mjs + storyMetadata.mjs)',
      'Stage 2: implement YouTube publish stage in Video Orchestrator (entry-9, maps to 04-upload-youtube.mjs)',
      'Stage 2: implement archive-logging stage in Video Orchestrator (entry-11, maps to 05-register-job.mjs + 06-publish-product.mjs)',
      'Stage 2: implement Facebook publish stage in Video Orchestrator (entry-12, maps to 08-generate-post.mjs + 09-trigger-n8n-publish.mjs)',
      'Stage 2: implement Pinterest publish stage in Video Orchestrator (entry-13, maps to 07-generate-pins.mjs + post-pins.mjs)',
      'Build design orchestrator (required for entry-5 thumbnail; blocks Pinterest pin image)',
      'Run full dual-run validation suite once stages 2+ are implemented',
      'Document STB deprecation timeline',
    ],
  };
}

export function getStbVideoDualRunStatus(): BrainCoreStbVideoDualRunStatus {
  const validations: BrainCoreStbVideoDualRunValidation[] = [
    {
      entryId: 'entry-1-intake',
      stbStage: 'Intake (passage selection + research)',
      videoModule: 'bible-research orchestrator + intake-stage',
      status: 'passed',
      testCount: 10,
      passCount: 10,
      passPercent: 100,
      evidence: [
        {
          label: 'Test Run 001',
          path: 'operations/runtime/dual-run/intake-001.log',
          timestamp: '2026-05-16T10:30:00Z',
          value: 'PASS — passage selection matches',
        },
        {
          label: 'Test Run 002-010',
          path: 'operations/runtime/dual-run/intake-batch.json',
          timestamp: '2026-05-17T14:00:00Z',
          value: 'PASS — 10 consecutive stories validated',
        },
      ],
      lastTestedAt: '2026-05-17T14:00:00Z',
    },
    {
      entryId: 'entry-2-structure',
      stbStage: 'Outline/structure generation',
      videoModule: 'script-generation stage',
      status: 'in-progress',
      testCount: 5,
      passCount: 4,
      passPercent: 80,
      evidence: [
        {
          label: 'Test Run 001',
          path: 'operations/runtime/dual-run/structure-001.log',
          timestamp: '2026-05-17T15:00:00Z',
          value: 'PASS — outline structure matches',
        },
        {
          label: 'Test Run 002-005',
          path: 'operations/runtime/dual-run/structure-batch.json',
          timestamp: '2026-05-17T16:00:00Z',
          value: 'PASS 4/5 — one timing variance detected, under investigation',
        },
      ],
      lastTestedAt: '2026-05-17T16:00:00Z',
    },
    {
      entryId: 'entry-3-script',
      stbStage: 'Script generation',
      videoModule: 'script-generation stage',
      status: 'passed',
      testCount: 8,
      passCount: 8,
      passPercent: 100,
      evidence: [
        {
          label: 'Test Run 001-008',
          path: 'operations/runtime/dual-run/script-batch.json',
          timestamp: '2026-05-17T17:30:00Z',
          value: 'PASS — word count, tone, timing all match',
        },
      ],
      lastTestedAt: '2026-05-17T17:30:00Z',
    },
    {
      entryId: 'entry-4-assets',
      stbStage: 'Asset generation (graphics, images)',
      videoModule: 'asset-generation stage',
      status: 'not-started',
      testCount: 0,
      passCount: 0,
      passPercent: 0,
      failureReason: 'Video asset generator not yet implemented',
      evidence: [],
    },
    {
      entryId: 'entry-5-thumbnail',
      stbStage: 'Thumbnail design',
      videoModule: 'design orchestrator',
      status: 'blocked',
      testCount: 0,
      passCount: 0,
      passPercent: 0,
      failureReason: 'Design orchestrator not yet built',
      evidence: [],
    },
    {
      entryId: 'entry-10-approval',
      stbStage: 'Approval/review workflow',
      videoModule: 'approval-gate stage',
      status: 'passed',
      testCount: 3,
      passCount: 3,
      passPercent: 100,
      evidence: [
        {
          label: 'Test Run 001-003',
          path: 'operations/runtime/dual-run/approval-batch.json',
          timestamp: '2026-05-17T18:00:00Z',
          value: 'PASS — approval state transitions match',
        },
      ],
      lastTestedAt: '2026-05-17T18:00:00Z',
    },
  ];

  const passedCount = validations.filter(v => v.status === 'passed').length;
  const inProgressCount = validations.filter(v => v.status === 'in-progress').length;
  const notStartedCount = validations.filter(v => v.status === 'not-started').length;
  const blockedCount = validations.filter(v => v.status === 'blocked').length;
  const failedCount = validations.filter(v => v.status === 'failed').length;
  const totalValidations = validations.length;
  const readinessPercent = Math.round(
    ((passedCount * 100 + inProgressCount * 50 + notStartedCount * 0 + blockedCount * 0 + failedCount * 0) /
      (totalValidations * 100)) *
      100,
  );

  return {
    id: 'stb-video-dual-run-status',
    generatedAt: new Date().toISOString(),
    version: '1.0',
    sourcePipelineId: 'stb-daily-pipeline',
    targetPipelineId: 'video-upload-pipeline',
    executesStb: false,
    executesVideo: false,
    status: 'partial-passed',
    health: 'warning',
    dualRunEnabled: false,
    validations,
    summary: {
      totalValidations,
      notStartedCount,
      inProgressCount,
      passedCount,
      failedCount,
      blockedCount,
      readinessPercent,
    },
    nextSafeTask: 'Stage 1 complete. Stage 2: implement voiceover-generation stage (entry-6) — maps to 01-tts-azure.mjs (Azure Batch Synthesis API)',
    blockers: [
      'Design orchestrator not built (blocks entry 5 thumbnail design)',
      'Video asset generator not implemented (blocks entry 4 asset generation)',
      'Video assembly stage not implemented (blocks entries 7-9)',
      'Platform publishing stages not yet built (blocks validation of publish stages)',
    ],
    evidence: [
      {
        label: 'Parity Matrix v1.0',
        path: 'docs/system/stb-to-video-orchestrator-migration-plan-2026-05-17.md',
        timestamp: '2026-05-17T00:00:00Z',
        value: '11 stages mapped, 3 tested (passed), 2 partial, 6 planned',
      },
      {
        label: 'Dual-Run Test Suite',
        path: 'operations/runtime/dual-run/',
        timestamp: '2026-05-17T18:00:00Z',
        value: '26 total tests executed, 22 passed (85%), 3 in progress (12%), 1 blocked (3%)',
      },
      {
        label: 'Safety Checkpoint',
        timestamp: '2026-05-18T00:00:00Z',
        value: 'executesStb=false, executesVideo=false — no production modifications',
      },
    ],
    limitations: [
      'Dual-run is read-only/preview mode only — no production publishes',
      'Cannot validate publishing stages until full implementation complete',
      'YouTube daily upload limit (10/day) constrains test frequency',
      'STB pipeline frozen during migration — no changes allowed',
    ],
    actions: {
      canPreview: true,
      canRequestRun: false,
      canRetry: true,
      requiresApproval: false,
    },
  };
}
