import type {
  BrainCoreControlledDualRunRequestRequirement,
  BrainCoreControlledDualRunRequestLifecycleStep,
  BrainCoreControlledDualRunRequestDesign,
  BrainCoreControlledDualRunRequestDesignResponse,
} from '../types/api.js';
import { readVideoProductionGate } from './video-orchestrator-production-gate.js';
import { readStbVideoDualRunEvidence } from './stb-video-dual-run-evidence.js';

function generateRequirements(): BrainCoreControlledDualRunRequestRequirement[] {
  const requirements: BrainCoreControlledDualRunRequestRequirement[] = [
    {
      id: 'req-candidate-selection',
      label: 'Candidate story selection criteria defined',
      category: 'candidate',
      status: 'blocked',
      severity: 'blocking',
      evidence: [
        'Production gate available showing planning chain complete for 5 test stories (052-056)',
        'Dual-run evidence available for same story set',
      ],
      blockers: [
        'Policy for candidate selection not defined',
        'Approval workflow for candidate selection not designed',
      ],
      nextSafeStep: 'Define candidate selection policy in execution-gates.ts or approval-policy module',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-preflight-production-gate',
      label: 'Production gate must not be ready (safety constraint)',
      category: 'preflight',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'Production gate status: blocked (confirmed)',
        'Video rendering not implemented (confirmed)',
        'Dual-run execution not available (confirmed)',
      ],
      blockers: [],
      nextSafeStep: 'Preflight production gate check passed',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-preflight-evidence-parity',
      label: 'Dual-run evidence must confirm no parity (safety constraint)',
      category: 'preflight',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'Dual-run evidence status: blocked',
        'No real dual-run execution implemented (confirmed)',
        'Output comparison not available (confirmed)',
      ],
      blockers: [],
      nextSafeStep: 'Preflight evidence check passed',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-approval-policy',
      label: 'Approval policy for dual-run request defined',
      category: 'approval',
      status: 'missing',
      severity: 'blocking',
      evidence: [],
      blockers: [
        'No approval policy module exists',
        'Approval gates for dual-run not specified',
        'Approval workflow design not completed',
      ],
      nextSafeStep: 'Design approval-policy module specifying what approvals are required before controlled-dual-run request',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-rollback-plan',
      label: 'Rollback plan defined',
      category: 'rollback',
      status: 'missing',
      severity: 'blocking',
      evidence: [],
      blockers: [
        'No rollback procedure specified',
        'No recovery steps documented',
        'No state reversion plan exists',
      ],
      nextSafeStep: 'Define rollback plan for failed dual-run (e.g., state reversion, error recovery)',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-execution-policy',
      label: 'Dual-run execution policy defined',
      category: 'execution-policy',
      status: 'missing',
      severity: 'blocking',
      evidence: [],
      blockers: [
        'Video rendering execution engine not implemented',
        'Dual-run orchestration not designed',
        'Execution isolation/sandboxing not specified',
      ],
      nextSafeStep: 'Design execution policy: how video orchestrator will be executed, what rendering layer will be used, how STB execution will be coordinated',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-evidence-inputs',
      label: 'Required evidence inputs specified',
      category: 'evidence',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'STB latest run available: story 052-056 metadata',
        'Video planning complete: intake → manual-export-package',
        'Dual-run evidence can be collected post-request',
      ],
      blockers: [],
      nextSafeStep: 'Evidence inputs satisfied; collection happens after controlled execution',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-safety-stb-protected',
      label: 'STB source of truth remains protected',
      category: 'safety',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'No STB execution in dual-run request design',
        'No STB mutation flags',
        'STB remains read-only source of truth',
      ],
      blockers: [],
      nextSafeStep: 'STB protection confirmed',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-safety-no-publishing',
      label: 'Publishing disabled',
      category: 'safety',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'publishesContent: false throughout request design',
        'No platform API calls',
        'No uploads or scheduling',
      ],
      blockers: [],
      nextSafeStep: 'Publishing safety confirmed',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'req-safety-no-approval-execution',
      label: 'Request design creates no executable approval',
      category: 'safety',
      status: 'satisfied',
      severity: 'info',
      evidence: [
        'No approval record created',
        'No action registered in action-registry',
        'No allowlist entry added',
        'Design-only, planning-only module',
      ],
      blockers: [],
      nextSafeStep: 'Approval execution safety confirmed',
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
  ];

  return requirements;
}

function generateLifecycleSteps(): BrainCoreControlledDualRunRequestLifecycleStep[] {
  const steps: BrainCoreControlledDualRunRequestLifecycleStep[] = [
    {
      id: 'step-1-select-candidate',
      sequence: 1,
      label: 'Select candidate story',
      status: 'blocked',
      description: 'Choose which story (052-056) to run in controlled dual-run. Requires candidate selection policy.',
      requiredBeforeExecution: true,
      blockers: ['Candidate selection policy not defined'],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-2-preflight-checks',
      sequence: 2,
      label: 'Run preflight checks',
      status: 'planned',
      description: 'Verify production gate, dual-run evidence, STB status, video planning chain. All read-only inspection.',
      requiredBeforeExecution: true,
      blockers: [],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-3-request-approval',
      sequence: 3,
      label: 'Request human approval',
      status: 'blocked',
      description: 'Request approval from human operator. Requires approval policy and approval workflow.',
      requiredBeforeExecution: true,
      blockers: ['Approval policy not defined', 'Approval workflow not implemented'],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-4-execute-controlled-dual-run',
      sequence: 4,
      label: 'Execute controlled dual-run',
      status: 'blocked',
      description: 'Run STB and Video Orchestrator in parallel. Requires execution policy and rendering engine.',
      requiredBeforeExecution: true,
      blockers: ['Video rendering engine not implemented', 'Dual-run orchestration not designed'],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-5-collect-evidence',
      sequence: 5,
      label: 'Collect dual-run evidence',
      status: 'planned',
      description: 'Record outputs, timing, metrics from both pipelines. Read-only evidence collection.',
      requiredBeforeExecution: false,
      blockers: [],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-6-compare-outputs',
      sequence: 6,
      label: 'Compare STB vs video outputs',
      status: 'blocked',
      description: 'Analyze parity and differences. Requires output comparison tooling.',
      requiredBeforeExecution: false,
      blockers: ['Output comparison tooling not implemented'],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-7-record-parity-evidence',
      sequence: 7,
      label: 'Record parity evidence',
      status: 'planned',
      description: 'Document comparison results and update dual-run evidence report.',
      requiredBeforeExecution: false,
      blockers: [],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
    {
      id: 'step-8-decide-continuation',
      sequence: 8,
      label: 'Decide whether to continue production acceleration',
      status: 'planned',
      description: 'Based on evidence, decide to proceed with video orchestrator production migration or continue iteration.',
      requiredBeforeExecution: false,
      blockers: [],
      safety: {
        readOnly: true,
        createsApproval: false,
        executesStb: false,
        executesVideo: false,
        writesFiles: false,
        publishesContent: false,
        decommissionsStb: false,
        writesToMind: false,
      },
    },
  ];

  return steps;
}

export function readControlledDualRunRequestDesign(): BrainCoreControlledDualRunRequestDesignResponse {
  const requirements = generateRequirements();
  const lifecycle = generateLifecycleSteps();

  const satisfied = requirements.filter(r => r.status === 'satisfied').length;
  const blocked = requirements.filter(r => r.status === 'blocked').length;
  const missing = requirements.filter(r => r.status === 'missing').length;
  const blockingSeverity = requirements.filter(r => r.severity === 'blocking').length;

  const design: BrainCoreControlledDualRunRequestDesign = {
    id: 'controlled-dual-run-request-design',
    generatedAt: new Date().toISOString(),
    status: blocked > 0 || missing > 0 ? 'blocked' : 'design-only',
    canRequestApproval: false,
    canExecute: false,
    requirements,
    lifecycle,
    summary: {
      totalRequirements: requirements.length,
      satisfiedCount: satisfied,
      blockedCount: blocked,
      missingCount: missing,
      blockingSeverityCount: blockingSeverity,
    },
    blockers: [
      'Candidate selection policy not defined',
      'Approval policy for dual-run not defined',
      'Rollback plan not defined',
      'Dual-run execution policy not designed',
      'Video rendering engine not implemented',
      'Output comparison tooling not implemented',
    ],
    nextSafeStep: 'Design approval policy and execution gates before attempting controlled dual-run request. Render readiness and export policy modules should precede execution design.',
    safety: {
      readOnly: true,
      createsApproval: false,
      executableActionRegistered: false,
      executesStb: false,
      executesVideo: false,
      writesFiles: false,
      publishesContent: false,
      decommissionsStb: false,
      writesToMind: false,
    },
  };

  return {
    design,
  };
}
