import type {
  BrainCoreVideoDesignProviderPromptReviewPolicyPlan,
  BrainCoreVideoDesignProviderPromptReviewPolicyPlanResponse,
} from '../types/api.js';

const policies: BrainCoreVideoDesignProviderPromptReviewPolicyPlan[] = [
  {
    id: 'image-generation-prompt-review',
    providerClass: 'image-generation',
    promptCategory: 'thumbnail-and-scene-generation',
    status: 'blocked',
    purpose: 'Define a human-reviewed prompt policy for future image-generation requests without generating or approving prompts.',
    allowedFuturePromptInputs: ['designPlanId', 'thumbnailPlanId', 'operatorApprovalRef', 'sandboxBoundaryRef', 'policyVersion'],
    disallowedPromptInputs: ['raw credentials', 'API keys', 'OAuth tokens', 'private notes', 'unredacted personal data', 'platform account secrets', 'filesystem paths outside approved sandbox', 'arbitrary shell text', 'STB mutation targets', 'publishing commands'],
    requiredHumanReviewChecks: [
      'Review for sandbox-only scope',
      'Review for theological and content-safety alignment',
      'Review for redaction of any sensitive references',
      'Review for no implicit provider execution or persistence',
    ],
    redactionRequirements: [
      'Prompt text may only contain redacted references and operator-approved labels.',
      'No raw credential, secret, or path material may be visible in review artifacts.',
      'Any future prompt preview must strip personal data and account identifiers.',
    ],
    theologicalContentSafetyRequirements: [
      'Avoid manipulative or sensational language.',
      'Keep scripture-sensitive language respectful and context-aware.',
      'Do not embed doctrinal assertions that were not operator-approved.',
    ],
    operatorApprovalGates: ['approved prompt review schema', 'approved redaction policy', 'approved theological safety review gate', 'approved provider onboarding gate'],
    auditRequirements: [
      'Audit records must preserve only approval state and redacted prompt references.',
      'No prompt payload, secret, or provider artifact may be persisted in audit output.',
      'Any future approval event requires immutable operator attribution.',
    ],
    blockers: ['No approved prompt review schema', 'No redaction policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the review checklist and redaction flow before any prompt preview or provider integration exists.',
    safety: {
      readOnly: true,
      promptReviewDesignOnly: true,
      promptGenerationEnabled: false,
      promptApprovalEnabled: false,
      approvedPromptPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'layout-rendering-prompt-review',
    providerClass: 'layout-rendering',
    promptCategory: 'layout-and-overlay-generation',
    status: 'blocked',
    purpose: 'Define a human-reviewed prompt policy for future layout-rendering requests without allowing prompt generation or provider calls.',
    allowedFuturePromptInputs: ['designSpecId', 'assemblyPlanId', 'platformLayoutPolicyRef', 'operatorApprovalRef', 'sandboxBoundaryRef'],
    disallowedPromptInputs: ['raw credentials', 'API keys', 'OAuth tokens', 'private notes', 'unredacted personal data', 'platform account secrets', 'filesystem paths outside approved sandbox', 'arbitrary shell text', 'STB mutation targets', 'publishing commands'],
    requiredHumanReviewChecks: [
      'Review for layout-only scope',
      'Review for path and overlay safety',
      'Review for sandbox and file-boundary compliance',
      'Review for no executable render instructions',
    ],
    redactionRequirements: [
      'Only sanitized layout references may appear in preview material.',
      'No source path, credential, or shell fragment may be exposed.',
      'Any future artifact preview must remove private data and platform secrets.',
    ],
    theologicalContentSafetyRequirements: [
      'Ensure on-screen text remains faithful and non-manipulative.',
      'Avoid content that distorts theological meaning through layout emphasis.',
      'Keep review labels descriptive, not persuasive.',
    ],
    operatorApprovalGates: ['approved prompt review schema', 'approved artifact sandbox boundary', 'approved theological safety review gate', 'approved prompt approval gate'],
    auditRequirements: [
      'Audit entries must remain prompt-reference only.',
      'No prompt body, path, or secret material may be written to audit storage.',
      'Operator approval references must be immutable and redacted.',
    ],
    blockers: ['No approved artifact sandbox boundary', 'No prompt review workflow', 'No operator approval workflow'],
    nextSafeStep: 'Design prompt review and sandbox policy before any layout-rendering prompt is approved or previewed.',
    safety: {
      readOnly: true,
      promptReviewDesignOnly: true,
      promptGenerationEnabled: false,
      promptApprovalEnabled: false,
      approvedPromptPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'brand-compliance-prompt-review',
    providerClass: 'brand-compliance',
    promptCategory: 'compliance-and-policy-checks',
    status: 'blocked',
    purpose: 'Define a human-reviewed prompt policy for future brand-compliance requests without exposing secrets or enabling provider interaction.',
    allowedFuturePromptInputs: ['metadataPlanId', 'platformPolicyRef', 'thumbnailPlanId', 'complianceChecklistRef', 'operatorReviewPacketRef'],
    disallowedPromptInputs: ['raw credentials', 'API keys', 'OAuth tokens', 'private notes', 'unredacted personal data', 'platform account secrets', 'filesystem paths outside approved sandbox', 'arbitrary shell text', 'STB mutation targets', 'publishing commands'],
    requiredHumanReviewChecks: [
      'Review for policy-only scope',
      'Review for content and compliance safety',
      'Review for redaction of private data and secrets',
      'Review for no implied publishing or mutation',
    ],
    redactionRequirements: [
      'Only policy-safe references may appear in review artifacts.',
      'No account identifier, secret, or private note may be exposed.',
      'Any future compliance preview must preserve redaction boundaries.',
    ],
    theologicalContentSafetyRequirements: [
      'Keep compliance language factual and non-authoritative beyond approved policy.',
      'Avoid implying spiritual endorsement in compliance summaries.',
      'Do not add doctrinal claims beyond the approved source material.',
    ],
    operatorApprovalGates: ['approved prompt review schema', 'approved compliance checklist', 'approved theological safety review gate', 'approved operator review gate'],
    auditRequirements: [
      'Audit output must remain redacted and reference-only.',
      'No prompt text or secret-bearing material may be persisted.',
      'Any approval or denial must record the operator decision only.',
    ],
    blockers: ['No approved compliance checklist', 'No prompt review workflow', 'No audit persistence policy'],
    nextSafeStep: 'Design the compliance checklist and redaction flow before any compliance prompt review exists.',
    safety: {
      readOnly: true,
      promptReviewDesignOnly: true,
      promptGenerationEnabled: false,
      promptApprovalEnabled: false,
      approvedPromptPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
];

export function readVideoDesignProviderPromptReviewPolicyPlans(): BrainCoreVideoDesignProviderPromptReviewPolicyPlanResponse {
  return {
    id: 'video-orchestrator-design-provider-prompt-review-policy-plan',
    status: 'blocked',
    phase: 'design-provider-prompt-review-policy-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      policyCount: policies.length,
      blockedCount: policies.filter((policy) => policy.status === 'blocked').length,
      promptGenerationCount: 0,
      providerCallCount: 0,
      approvedPromptCount: 0,
      persistedPromptCount: 0,
    },
    policies,
    safety: {
      readOnly: true,
      promptReviewDesignOnly: true,
      promptGenerationEnabled: false,
      promptApprovalEnabled: false,
      approvedPromptPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved prompt review schema', 'No prompt approval workflow', 'No compliance checklist'],
    nextSafeStep: 'Design provider compliance checklist and prompt redaction workflow before any prompt review approval path exists.',
  };
}

export function readVideoDesignProviderPromptReviewPolicyPlan(
  id: string,
): BrainCoreVideoDesignProviderPromptReviewPolicyPlan | undefined {
  return policies.find((policy) => policy.id === id || policy.providerClass === id);
}
