import type {
  BrainCoreVideoArtifactSandboxProviderHandoffPlan,
  BrainCoreVideoArtifactSandboxProviderHandoffPlanResponse,
} from '../types/api.js';

const handoffPlans: BrainCoreVideoArtifactSandboxProviderHandoffPlan[] = [
  {
    id: 'image-generation-artifact-handoff',
    providerClass: 'image-generation',
    handoffCategory: 'thumbnail-and-scene-artifacts',
    status: 'blocked',
    purpose: 'Define a future artifact handoff boundary for image-generation providers without creating, writing, or persisting artifacts.',
    allowedFutureHandoffInputs: ['sourcePlanId', 'promptReviewPolicyId', 'credentialIsolationPlanId', 'sandboxPolicyRef', 'redactionPolicyRef', 'operatorApprovalRef'],
    disallowedHandoffInputs: [
      'raw generated files',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'publishing commands',
      'platform upload payloads',
      'arbitrary shell text',
    ],
    proposedManifestFields: [
      'artifactId',
      'providerClass',
      'sourcePlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'sandboxPolicyRef',
      'redactionPolicyRef',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
      'expiresAtPlaceholder',
    ],
    proposedSandboxBoundaryChecks: [
      'Validate that any future artifact path stays inside the approved sandbox root.',
      'Reject any absolute path, traversal segment, or out-of-sandbox reference.',
      'Reject any raw artifact bytes, generated file path, or upload payload.',
      'Require redaction policy and operator approval before any manifest reference exists.',
    ],
    redactionRequirements: [
      'No raw artifact content may appear in handoff artifacts.',
      'No secret-bearing field or file path may be displayed.',
      'Any future manifest preview must remain reference-only and redacted.',
    ],
    requiredApprovalGates: [
      'approved sandbox boundary policy',
      'approved redaction policy',
      'approved prompt review policy',
      'approved credential isolation policy',
    ],
    auditRequirements: [
      'Audit output must be reference-only and immutable when approved.',
      'No artifact bytes, upload payloads, or secret material may be persisted.',
      'Any future handoff event must record operator approval state only.',
    ],
    blockers: ['No approved sandbox boundary policy', 'No artifact manifest policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the sandbox boundary checks and manifest reference shape before any artifact handoff is allowed.',
    safety: {
      readOnly: true,
      handoffDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      artifactManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      sandboxWriteEnabled: false,
      sandboxReadEnabled: false,
      credentialAccessEnabled: false,
      rawArtifactAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'layout-rendering-artifact-handoff',
    providerClass: 'layout-rendering',
    handoffCategory: 'layout-and-overlay-artifacts',
    status: 'blocked',
    purpose: 'Define a future artifact handoff boundary for layout-rendering providers without allowing sandbox writes or persistence.',
    allowedFutureHandoffInputs: ['sourcePlanId', 'promptReviewPolicyId', 'credentialIsolationPlanId', 'sandboxPolicyRef', 'redactionPolicyRef', 'operatorApprovalRef'],
    disallowedHandoffInputs: [
      'raw generated files',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'publishing commands',
      'platform upload payloads',
      'arbitrary shell text',
    ],
    proposedManifestFields: [
      'artifactId',
      'providerClass',
      'sourcePlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'sandboxPolicyRef',
      'redactionPolicyRef',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
      'expiresAtPlaceholder',
    ],
    proposedSandboxBoundaryChecks: [
      'Require layout outputs to remain in a sandbox placeholder only.',
      'Reject any request to materialize or export rendered files.',
      'Reject platform upload payloads and shell-based export commands.',
      'Require redaction and approval before any future manifest reference.',
    ],
    redactionRequirements: [
      'No layout output may be shown as raw files or byte content.',
      'No secret or platform identifier may appear in a handoff summary.',
      'Any future preview must be sanitized to reference-only metadata.',
    ],
    requiredApprovalGates: [
      'approved sandbox boundary policy',
      'approved redaction policy',
      'approved prompt review policy',
      'approved operator review gate',
    ],
    auditRequirements: [
      'Audit records must remain manifest-reference only.',
      'No rendered file path, byte payload, or secret material may be persisted.',
      'Operator approval records must be immutable and redacted.',
    ],
    blockers: ['No approved layout sandbox boundary', 'No artifact manifest policy', 'No approval workflow'],
    nextSafeStep: 'Design the layout sandbox boundary and redaction policy before any handoff manifest can be referenced.',
    safety: {
      readOnly: true,
      handoffDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      artifactManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      sandboxWriteEnabled: false,
      sandboxReadEnabled: false,
      credentialAccessEnabled: false,
      rawArtifactAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'brand-compliance-artifact-handoff',
    providerClass: 'brand-compliance',
    handoffCategory: 'compliance-and-review-artifacts',
    status: 'blocked',
    purpose: 'Define a future artifact handoff boundary for brand-compliance providers without exposing or persisting artifact data.',
    allowedFutureHandoffInputs: ['sourcePlanId', 'promptReviewPolicyId', 'credentialIsolationPlanId', 'sandboxPolicyRef', 'redactionPolicyRef', 'operatorApprovalRef'],
    disallowedHandoffInputs: [
      'raw generated files',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'publishing commands',
      'platform upload payloads',
      'arbitrary shell text',
    ],
    proposedManifestFields: [
      'artifactId',
      'providerClass',
      'sourcePlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'sandboxPolicyRef',
      'redactionPolicyRef',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
      'expiresAtPlaceholder',
    ],
    proposedSandboxBoundaryChecks: [
      'Require compliance artifacts to remain reference-only.',
      'Reject any raw artifact bytes or external upload payload.',
      'Reject any filesystem path outside approved sandbox scope.',
      'Require operator approval before any future manifest reference.',
    ],
    redactionRequirements: [
      'No personal data or secret-bearing material may appear in the handoff summary.',
      'No platform identifier or raw file path may be displayed.',
      'Any future preview must stay redacted and reference-only.',
    ],
    requiredApprovalGates: [
      'approved sandbox boundary policy',
      'approved redaction policy',
      'approved compliance review policy',
      'approved operator review gate',
    ],
    auditRequirements: [
      'Audit records must not persist artifact bytes or secret data.',
      'Any future compliance handoff must record the operator decision only.',
      'Manifest references must remain immutable once approved.',
    ],
    blockers: ['No approved compliance sandbox boundary', 'No artifact manifest policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the compliance handoff manifest and sandbox boundary checks before any provider handoff is allowed.',
    safety: {
      readOnly: true,
      handoffDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      artifactManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      sandboxWriteEnabled: false,
      sandboxReadEnabled: false,
      credentialAccessEnabled: false,
      rawArtifactAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
];

export function readVideoArtifactSandboxProviderHandoffPlans(): BrainCoreVideoArtifactSandboxProviderHandoffPlanResponse {
  return {
    id: 'video-orchestrator-artifact-sandbox-provider-handoff-plan',
    status: 'blocked',
    phase: 'artifact-sandbox-provider-handoff-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      handoffPlanCount: handoffPlans.length,
      blockedCount: handoffPlans.filter((plan) => plan.status === 'blocked').length,
      providerConfiguredCount: 0,
      providerCallCount: 0,
      artifactPersistedCount: 0,
      sandboxWriteCount: 0,
      manifestCreatedCount: 0,
    },
    handoffPlans,
    safety: {
      readOnly: true,
      handoffDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      artifactManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      sandboxWriteEnabled: false,
      sandboxReadEnabled: false,
      credentialAccessEnabled: false,
      rawArtifactAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved sandbox boundary policy', 'No artifact manifest policy', 'No operator approval workflow'],
    nextSafeStep: 'Design sandbox boundary checks and manifest redaction policy before any artifact handoff can be referenced.',
  };
}

export function readVideoArtifactSandboxProviderHandoffPlan(
  id: string,
): BrainCoreVideoArtifactSandboxProviderHandoffPlan | undefined {
  return handoffPlans.find((plan) => plan.id === id || plan.providerClass === id);
}
