import type {
  BrainCoreVideoDesignProviderCredentialIsolationPlan,
  BrainCoreVideoDesignProviderCredentialIsolationPlanResponse,
} from '../types/api.js';

const plans: BrainCoreVideoDesignProviderCredentialIsolationPlan[] = [
  {
    id: 'image-generation-provider-credentials',
    providerClass: 'image-generation-provider',
    status: 'blocked',
    purpose: 'Define a future credential isolation boundary for image-generation providers without storing or reading secrets.',
    credentialReferenceModel: 'A stable, redacted reference object that can point to a future approved credential record without exposing secret material.',
    allowedFutureCredentialReferenceFields: ['credentialRefId', 'providerClass', 'credentialPurpose', 'approvalRef', 'redactionPolicyRef', 'rotationPolicyRef'],
    disallowedFields: ['raw tokens', 'API keys', 'cookies', 'OAuth refresh tokens', 'private keys', '.env dumps', 'filesystem credential paths', 'platform account IDs'],
    redactionRequirements: [
      'Only opaque reference identifiers may be shown in UI or logs.',
      'No provider secret value, token fragment, or file path may be emitted.',
      'Any future audit trail must redact all credential-bearing fields before persistence.',
    ],
    operatorApprovalGates: ['approved credential reference schema', 'approved redaction policy', 'approved operator credential review gate', 'approved provider onboarding gate'],
    auditRequirements: [
      'Future events must record only reference identifiers and approval state.',
      'Credential material must never be persisted in audit output.',
      'Any future access attempt requires a separate immutable approval record.',
    ],
    blockers: ['No approved credential reference schema', 'No credential redaction policy', 'No provider onboarding approval'],
    nextSafeStep: 'Design the credential reference schema and approval workflow before any provider credential configuration exists.',
    safety: {
      readOnly: true,
      credentialIsolationDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      secretMaterialStored: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemCredentialAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'layout-rendering-provider-credentials',
    providerClass: 'layout-rendering-provider',
    status: 'blocked',
    purpose: 'Define a future credential isolation boundary for layout-rendering providers without enabling any runtime access.',
    credentialReferenceModel: 'A redacted provider credential reference that can be approved independently from any render job or output artifact.',
    allowedFutureCredentialReferenceFields: ['credentialRefId', 'providerClass', 'credentialPurpose', 'approvalRef', 'sandboxBoundaryRef', 'redactionPolicyRef'],
    disallowedFields: ['raw tokens', 'API keys', 'cookies', 'OAuth refresh tokens', 'private keys', '.env dumps', 'filesystem credential paths', 'platform account IDs'],
    redactionRequirements: [
      'Never surface raw credential values in artifact previews.',
      'Strip secret-bearing metadata from any future audit summary.',
      'Keep credential references opaque and non-derivable.',
    ],
    operatorApprovalGates: ['approved credential reference schema', 'approved artifact sandbox boundary', 'approved operator review gate', 'approved credential isolation gate'],
    auditRequirements: [
      'Audit entries may mention the credential reference id only.',
      'No render input, output, or credential material may be persisted together.',
      'Future audit access must remain approval-gated and redacted.',
    ],
    blockers: ['No approved artifact sandbox boundary', 'No credential reference schema', 'No operator approval workflow'],
    nextSafeStep: 'Design the redacted credential reference and sandbox approval flow before any layout-rendering provider connection.',
    safety: {
      readOnly: true,
      credentialIsolationDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      secretMaterialStored: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemCredentialAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'brand-compliance-provider-credentials',
    providerClass: 'brand-compliance-provider',
    status: 'blocked',
    purpose: 'Define a future credential isolation boundary for brand-compliance providers without storing secrets or platform identifiers.',
    credentialReferenceModel: 'A policy-scoped credential reference that can be approved for compliance checks without exposing the underlying secret store.',
    allowedFutureCredentialReferenceFields: ['credentialRefId', 'providerClass', 'credentialPurpose', 'approvalRef', 'compliancePolicyRef', 'redactionPolicyRef'],
    disallowedFields: ['raw tokens', 'API keys', 'cookies', 'OAuth refresh tokens', 'private keys', '.env dumps', 'filesystem credential paths', 'platform account IDs'],
    redactionRequirements: [
      'Only high-level policy references may appear in future output.',
      'Compliance evidence must omit credential values and account identifiers.',
      'Any future operator-facing view must show redacted references only.',
    ],
    operatorApprovalGates: ['approved credential reference schema', 'approved compliance evidence policy', 'approved operator review gate', 'approved credential isolation gate'],
    auditRequirements: [
      'Audit records must be reference-only and redacted.',
      'No secret-bearing content may be written to logs or archives.',
      'Any future review packet requires explicit approval before disclosure.',
    ],
    blockers: ['No approved compliance evidence policy', 'No credential reference schema', 'No immutable audit trail approval'],
    nextSafeStep: 'Design the compliance evidence and redaction policy before any brand-compliance provider is configured.',
    safety: {
      readOnly: true,
      credentialIsolationDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      secretMaterialStored: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemCredentialAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
];

export function readVideoDesignProviderCredentialIsolationPlans(): BrainCoreVideoDesignProviderCredentialIsolationPlanResponse {
  return {
    id: 'video-orchestrator-design-provider-credential-isolation-plan',
    status: 'blocked',
    phase: 'design-provider-credential-isolation-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      planCount: plans.length,
      blockedCount: plans.filter((plan) => plan.status === 'blocked').length,
      credentialConfiguredCount: 0,
      credentialAccessCount: 0,
      secretMaterialStoredCount: 0,
      providerCallCount: 0,
    },
    plans,
    safety: {
      readOnly: true,
      credentialIsolationDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      credentialAccessEnabled: false,
      secretMaterialStored: false,
      rawCredentialDisplayEnabled: false,
      envReadEnabled: false,
      filesystemCredentialAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved credential reference schema', 'No credential redaction policy', 'No provider onboarding approval'],
    nextSafeStep: 'Design the credential reference schema and approval workflow before any provider credential configuration exists.',
  };
}

export function readVideoDesignProviderCredentialIsolationPlan(
  id: string,
): BrainCoreVideoDesignProviderCredentialIsolationPlan | undefined {
  return plans.find((plan) => plan.id === id || plan.providerClass === id);
}
