import type {
  BrainCoreVideoProviderRequestEnvelopeScaffold,
  BrainCoreVideoProviderRequestEnvelopeScaffoldResponse,
} from '../types/api.js';

const requiredReferences = [
  'provider-request-wrapper-scaffold',
  'provider-wrapper-validation-harness',
  'credential-reference-scaffold',
  'design-provider-prompt-review-policy-plan',
  'prompt-review-ux-implementation-plan',
  'artifact-sandbox-provider-handoff-plan',
  'provider-output-redaction-policy-plan',
  'design-provider-compliance-checklist-plan',
  'provider-audit-persistence-boundary-plan',
] as const;

const safety: BrainCoreVideoProviderRequestEnvelopeScaffold['safety'] = {
  readOnlyStatusEndpoint: true,
  requestEnvelopeScaffoldingOnly: true,
  sendableEnvelopeImplemented: false,
  providerConfigured: false,
  providerCallsEnabled: false,
  credentialAccessEnabled: false,
  networkAccessEnabled: false,
  promptGenerationEnabled: false,
  imageGenerationEnabled: false,
  artifactPersistenceEnabled: false,
  auditPersistenceEnabled: false,
  filesystemAccessEnabled: false,
  writesFiles: false,
  publishesContent: false,
  writesToMind: false,
  executesVideo: false,
  postRoutesAdded: false,
  brainConsoleMutationControlsEnabled: false,
};

export function readVideoProviderRequestEnvelopeScaffold(): BrainCoreVideoProviderRequestEnvelopeScaffoldResponse {
  return {
    envelope: {
      id: 'video-orchestrator-provider-request-envelope-scaffold',
      status: 'scaffolded-disabled',
      phase: 'provider-request-envelope-scaffolding-only',
      envelopeShape: {
        requestIdPlaceholder: 'request id placeholder',
        providerClass: 'supported provider class',
        sourcePlanId: 'source plan id',
        requestWrapperScaffoldRef: 'provider request wrapper scaffold ref',
        credentialReferenceRef: 'credential reference ref',
        promptReviewPolicyRef: 'prompt review policy ref',
        promptReviewUxRef: 'prompt review ux ref',
        artifactSandboxHandoffRef: 'artifact sandbox handoff ref',
        outputRedactionPolicyRef: 'output redaction policy ref',
        complianceChecklistRef: 'compliance checklist ref',
        auditRefPlaceholder: 'audit ref placeholder',
        createdAtPlaceholder: 'created at placeholder',
      },
      requiredReferences: [...requiredReferences],
      validationRules: [
        'envelope is inert and cannot be sent',
        'providerClass must be supported',
        'requestWrapperScaffoldRef is required',
        'credentialReferenceRef is required',
        'promptReviewPolicyRef is required',
        'promptReviewUxRef is required',
        'artifactSandboxHandoffRef is required',
        'outputRedactionPolicyRef is required',
        'complianceChecklistRef is required',
        'auditRefPlaceholder is required',
        'createdAtPlaceholder is required',
        'provider calls are blocked in this scaffold phase',
        'credentials are blocked in this scaffold phase',
        'network access is blocked in this scaffold phase',
      ],
      disabledCapabilities: [
        { capability: 'provider calls', enabled: false as const },
        { capability: 'network access', enabled: false as const },
        { capability: 'credential access', enabled: false as const },
        { capability: 'prompt generation', enabled: false as const },
        { capability: 'image generation', enabled: false as const },
        { capability: 'artifact writes', enabled: false as const },
        { capability: 'audit persistence', enabled: false as const },
        { capability: 'POST routes', enabled: false as const },
        { capability: 'Brain Console mutation controls', enabled: false as const },
      ],
      summary: {
        envelopeShapeCount: 1,
        supportedProviderClassCount: 3,
        sendableEnvelopeCount: 0,
        providerCallCount: 0,
        networkAccessCount: 0,
        credentialAccessCount: 0,
      },
      safety,
      blockers: [
        'sendable envelopes remain blocked',
        'provider calls remain blocked',
        'credentials remain inaccessible',
        'Brain Console remains read-only',
      ],
      nextSafeStep: 'Await explicit approval before any provider request envelope implementation beyond inert scaffolding.',
    },
  };
}
