import type {
  BrainCoreVideoArchiveLoggingPlan,
  BrainCoreVideoArchiveLoggingPlanResponse,
} from '../types/api.js';

const plans: BrainCoreVideoArchiveLoggingPlan[] = [
  {
    id: 'archive-log-story-052-preview-lifecycle',
    storyId: 'story-052',
    sourcePlanIds: ['video-intake-story-052', 'video-research-story-052', 'video-script-story-052', 'thumbnail-story-052-faith-under-pressure'],
    title: 'Story 052 preview lifecycle archive/log plan',
    status: 'blocked',
    archiveIntent: 'Define what would be recorded for preview lifecycle traceability without writing an archive record.',
    recordShape: {
      recordType: 'preview_lifecycle_summary',
      identityFields: ['storyId', 'sourceEpisodeId', 'planIds', 'policyVersion'],
      evidenceFields: ['intakePlanRef', 'researchBriefRef', 'scriptPlanRef', 'thumbnailPlanRef', 'safetyFlags'],
      auditFields: ['operatorContextPlaceholder', 'generatedAtPlaceholder', 'approvalStatePlaceholder'],
      retentionPolicy: 'future append-only archive store, no persistence in this phase',
    },
    loggingChecks: [
      {
        id: 'source-plan-references-present',
        label: 'Source plan references present',
        status: 'planned',
        required: true,
        description: 'Every future archive record must reference source preview plans by stable id.',
      },
      {
        id: 'safety-flags-preserved',
        label: 'Safety flags preserved',
        status: 'planned',
        required: true,
        description: 'Archive metadata must preserve disabled execution/write/publish flags.',
      },
      {
        id: 'no-runtime-log-ingest',
        label: 'No runtime log ingest',
        status: 'blocked',
        required: true,
        description: 'No runtime logs are read or persisted during this design-only phase.',
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      archiveWritesEnabled: false,
      auditPersistenceEnabled: false,
      runtimeLogIngestEnabled: false,
      deletesFiles: false,
      movesFiles: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      decommissionsStb: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['No approved append-only archive store', 'No audit persistence policy enabled', 'No runtime log ingestion boundary approved'],
    nextSafeStep: 'Design archive storage and audit retention policy separately before enabling persistence.',
  },
  {
    id: 'archive-log-story-053-review-evidence',
    storyId: 'story-053',
    sourcePlanIds: ['video-intake-story-053', 'video-design-story-053', 'thumbnail-story-053-forgiveness-turning-point'],
    title: 'Story 053 review evidence archive/log plan',
    status: 'blocked',
    archiveIntent: 'Define review evidence archive metadata for future operator comparison without persisting anything.',
    recordShape: {
      recordType: 'review_evidence_summary',
      identityFields: ['storyId', 'reviewPacketIdPlaceholder', 'planIds', 'policyVersion'],
      evidenceFields: ['designPlanRef', 'thumbnailPlanRef', 'comparisonSchemaRef', 'blockerSummary'],
      auditFields: ['reviewerPlaceholder', 'reviewWindowPlaceholder', 'decisionSnapshotPlaceholder'],
      retentionPolicy: 'future immutable audit trail linkage, no persistence in this phase',
    },
    loggingChecks: [
      {
        id: 'review-packet-reference-required',
        label: 'Review packet reference required',
        status: 'planned',
        required: true,
        description: 'Future archive records must link to operator review packet evidence.',
      },
      {
        id: 'decision-snapshot-required',
        label: 'Decision snapshot required',
        status: 'planned',
        required: true,
        description: 'Future archive records must reference immutable operator decisions when approvals exist.',
      },
      {
        id: 'no-archive-record-created',
        label: 'No archive record created',
        status: 'blocked',
        required: true,
        description: 'This endpoint only describes the future record shape.',
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      archiveWritesEnabled: false,
      auditPersistenceEnabled: false,
      runtimeLogIngestEnabled: false,
      deletesFiles: false,
      movesFiles: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      decommissionsStb: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['No approved append-only archive store', 'No audit persistence policy enabled', 'No runtime log ingestion boundary approved'],
    nextSafeStep: 'Design archive storage and audit retention policy separately before enabling persistence.',
  },
  {
    id: 'archive-log-story-054-cutover-readiness',
    storyId: 'story-054',
    sourcePlanIds: ['video-production-gate', 'video-release-candidate-readiness', 'thumbnail-story-054-courage-at-the-threshold'],
    title: 'Story 054 cutover readiness archive/log plan',
    status: 'blocked',
    archiveIntent: 'Define future cutover-readiness logging for decommission safeguards without starting decommission.',
    recordShape: {
      recordType: 'cutover_readiness_summary',
      identityFields: ['storyId', 'releaseCandidateIdPlaceholder', 'gateIds', 'policyVersion'],
      evidenceFields: ['productionGateRef', 'releaseCandidateReadinessRef', 'stbProtectionRef', 'rollbackPlanRef'],
      auditFields: ['operatorApprovalPlaceholder', 'secondApprovalPlaceholder', 'expiryPlaceholder'],
      retentionPolicy: 'future compliance evidence packet linkage, no persistence in this phase',
    },
    loggingChecks: [
      {
        id: 'stb-protection-reference-required',
        label: 'STB protection reference required',
        status: 'planned',
        required: true,
        description: 'Future archive records must prove STB protection before any cutover.',
      },
      {
        id: 'rollback-reference-required',
        label: 'Rollback reference required',
        status: 'planned',
        required: true,
        description: 'Future archive records must include rollback and cleanup evidence references.',
      },
      {
        id: 'decommission-not-started',
        label: 'Decommission not started',
        status: 'blocked',
        required: true,
        description: 'This plan cannot start or imply STB decommission.',
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      archiveWritesEnabled: false,
      auditPersistenceEnabled: false,
      runtimeLogIngestEnabled: false,
      deletesFiles: false,
      movesFiles: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      decommissionsStb: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['No approved append-only archive store', 'No audit persistence policy enabled', 'No runtime log ingestion boundary approved'],
    nextSafeStep: 'Design archive storage and audit retention policy separately before enabling persistence.',
  },
];

export function readVideoArchiveLoggingPlans(): BrainCoreVideoArchiveLoggingPlanResponse {
  return {
    id: 'video-orchestrator-archive-logging-plan',
    status: 'blocked',
    phase: 'archive-logging-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      planCount: plans.length,
      recordShapeCount: plans.length,
      loggingCheckCount: plans.reduce((count, plan) => count + plan.loggingChecks.length, 0),
      blockedCount: plans.filter((plan) => plan.status === 'blocked').length,
      persistedRecordCount: 0,
    },
    plans,
    safety: {
      readOnly: true,
      designOnly: true,
      archiveWritesEnabled: false,
      auditPersistenceEnabled: false,
      runtimeLogIngestEnabled: false,
      deletesFiles: false,
      movesFiles: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      decommissionsStb: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['No approved append-only archive store', 'No audit persistence policy enabled', 'No runtime log ingestion boundary approved'],
    nextSafeStep: 'Design archive storage and audit retention policy separately before enabling persistence.',
  };
}

export function readVideoArchiveLoggingPlan(id: string): BrainCoreVideoArchiveLoggingPlan | undefined {
  return plans.find((plan) => plan.id === id || plan.storyId === id);
}
