import type {
  BrainCoreVideoThumbnailDesignPlan,
  BrainCoreVideoThumbnailDesignPlanResponse,
} from '../types/api.js';

const plans: BrainCoreVideoThumbnailDesignPlan[] = [
  {
    id: 'thumbnail-story-052-faith-under-pressure',
    storyId: 'story-052',
    sourcePlanId: 'video-design-story-052',
    title: 'Faith Under Pressure thumbnail plan',
    status: 'blocked',
    designIntent: 'High-contrast visual tension with a single readable promise line and no generated artwork.',
    composition: {
      layout: 'single focal subject area with supporting scripture context',
      foreground: 'operator-provided or future-approved visual placeholder only',
      background: 'muted contrast field, no rendered image asset',
      textOverlay: 'short title placeholder, max six words',
      safeArea: 'center-safe text and right-safe face/object zone',
    },
    variants: [
      {
        id: 'story-052-variant-a',
        label: 'Contrast promise',
        status: 'planned',
        hypothesis: 'A direct promise line improves click clarity without sensationalism.',
        textOverlay: 'Faith Under Pressure',
        generatedAsset: false,
      },
      {
        id: 'story-052-variant-b',
        label: 'Question hook',
        status: 'planned',
        hypothesis: 'A question hook can clarify tension while staying theologically neutral.',
        textOverlay: 'Will Faith Hold?',
        generatedAsset: false,
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      callsExternalAI: false,
      generatesImages: false,
      rendersVideo: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['Design orchestrator execution is not enabled', 'No approved image generation provider', 'No artifact sandbox/output path policy'],
    nextSafeStep: 'Keep thumbnail planning as design-only until the design orchestrator and artifact policy are approved.',
  },
  {
    id: 'thumbnail-story-053-forgiveness-turning-point',
    storyId: 'story-053',
    sourcePlanId: 'video-design-story-053',
    title: 'Forgiveness Turning Point thumbnail plan',
    status: 'blocked',
    designIntent: 'Warm visual contrast between burden and release, using placeholder-only art direction.',
    composition: {
      layout: 'left tension/right release split composition',
      foreground: 'human silhouette placeholder, no generated image',
      background: 'soft transition field, future asset required',
      textOverlay: 'short restoration phrase',
      safeArea: 'text in lower-left third, no edge-locked typography',
    },
    variants: [
      {
        id: 'story-053-variant-a',
        label: 'Release promise',
        status: 'planned',
        hypothesis: 'Clear restoration language can pair with a warm visual field.',
        textOverlay: 'Forgiven Again',
        generatedAsset: false,
      },
      {
        id: 'story-053-variant-b',
        label: 'Conflict hook',
        status: 'planned',
        hypothesis: 'A contrast headline can signal the turning point without exaggeration.',
        textOverlay: 'The Turning Point',
        generatedAsset: false,
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      callsExternalAI: false,
      generatesImages: false,
      rendersVideo: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['Design orchestrator execution is not enabled', 'No approved image generation provider', 'No artifact sandbox/output path policy'],
    nextSafeStep: 'Keep thumbnail planning as design-only until the design orchestrator and artifact policy are approved.',
  },
  {
    id: 'thumbnail-story-054-courage-at-the-threshold',
    storyId: 'story-054',
    sourcePlanId: 'video-design-story-054',
    title: 'Courage at the Threshold thumbnail plan',
    status: 'blocked',
    designIntent: 'Threshold/doorway metaphor with high readability and no generated art execution.',
    composition: {
      layout: 'center threshold shape with text in lower safe area',
      foreground: 'doorway or path placeholder only',
      background: 'future-approved visual asset required',
      textOverlay: 'courage-focused phrase',
      safeArea: 'avoid top-right platform overlays and bottom captions',
    },
    variants: [
      {
        id: 'story-054-variant-a',
        label: 'Threshold visual',
        status: 'planned',
        hypothesis: 'A threshold metaphor can communicate decision quickly.',
        textOverlay: 'Step Forward',
        generatedAsset: false,
      },
      {
        id: 'story-054-variant-b',
        label: 'Courage line',
        status: 'planned',
        hypothesis: 'Direct courage wording can improve emotional clarity.',
        textOverlay: 'Courage Begins Here',
        generatedAsset: false,
      },
    ],
    safety: {
      readOnly: true,
      designOnly: true,
      callsExternalAI: false,
      generatesImages: false,
      rendersVideo: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['Design orchestrator execution is not enabled', 'No approved image generation provider', 'No artifact sandbox/output path policy'],
    nextSafeStep: 'Keep thumbnail planning as design-only until the design orchestrator and artifact policy are approved.',
  },
];

export function readVideoThumbnailDesignPlans(): BrainCoreVideoThumbnailDesignPlanResponse {
  return {
    id: 'video-orchestrator-thumbnail-design-plan',
    status: 'blocked',
    phase: 'thumbnail-design-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      planCount: plans.length,
      variantCount: plans.reduce((count, plan) => count + plan.variants.length, 0),
      blockedCount: plans.filter((plan) => plan.status === 'blocked').length,
      generatedAssetCount: 0,
    },
    plans,
    safety: {
      readOnly: true,
      designOnly: true,
      callsExternalAI: false,
      generatesImages: false,
      rendersVideo: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesStb: false,
      executesVideo: false,
    },
    blockers: ['Design orchestrator execution is not enabled', 'No approved image generation provider', 'No artifact sandbox/output path policy'],
    nextSafeStep: 'Design the image-generation/artifact sandbox boundary before enabling thumbnail generation.',
  };
}

export function readVideoThumbnailDesignPlan(id: string): BrainCoreVideoThumbnailDesignPlan | undefined {
  return plans.find((plan) => plan.id === id || plan.storyId === id);
}
