import type {
  BrainCoreVideoDesignProviderComplianceChecklistPlan,
  BrainCoreVideoDesignProviderComplianceChecklistPlanResponse,
} from '../types/api.js';

const checklists: BrainCoreVideoDesignProviderComplianceChecklistPlan[] = [
  {
    id: 'image-generation-compliance-checklist',
    providerClass: 'image-generation',
    checklistCategory: 'image-generation-compliance',
    status: 'blocked',
    purpose: 'Define a future compliance checklist for image-generation providers without enabling compliance evaluation or persistence.',
    requiredChecks: [
      'credential isolation plan reviewed',
      'prompt review policy reviewed',
      'artifact sandbox handoff plan reviewed',
      'output redaction policy reviewed',
      'provider boundary plan reviewed',
      'operator approval gate defined',
      'audit reference policy defined',
      'rollback/cleanup policy linked',
      'no STB mutation path confirmed',
      'no publishing path confirmed',
    ],
    blockedChecks: [
      'compliance evaluation is not enabled',
      'compliance records are not persisted',
      'provider output is not inspected directly',
    ],
    evidenceReferencesRequiredBeforeFutureProviderEnablement: [
      'credential-isolation-plan-ref',
      'prompt-review-policy-ref',
      'artifact-sandbox-handoff-plan-ref',
      'output-redaction-policy-ref',
      'provider-boundary-plan-ref',
      'audit-reference-policy-ref',
      'rollback-cleanup-policy-ref',
    ],
    disallowedComplianceEvidenceSources: [
      'raw provider responses',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'unredacted logs',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'generated media files',
      'arbitrary shell output',
    ],
    operatorReviewGates: ['approved checklist schema', 'approved evidence reference policy', 'approved operator review gate', 'approved rollback linkage'],
    auditRequirements: [
      'Audit output must remain reference-only.',
      'No compliance record may be persisted in this phase.',
      'Any future review state must remain redacted and immutable.',
    ],
    blockers: ['No approved checklist schema', 'No evidence reference policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the checklist reference model and operator review gates before any compliance evaluation exists.',
    safety: {
      readOnly: true,
      complianceChecklistDesignOnly: true,
      complianceEvaluationEnabled: false,
      complianceRecordPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      credentialAccessEnabled: false,
      auditPersistenceEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'layout-rendering-compliance-checklist',
    providerClass: 'layout-rendering',
    checklistCategory: 'layout-rendering-compliance',
    status: 'blocked',
    purpose: 'Define a future compliance checklist for layout-rendering providers without enabling compliance evaluation or persistence.',
    requiredChecks: [
      'credential isolation plan reviewed',
      'prompt review policy reviewed',
      'artifact sandbox handoff plan reviewed',
      'output redaction policy reviewed',
      'provider boundary plan reviewed',
      'operator approval gate defined',
      'audit reference policy defined',
      'rollback/cleanup policy linked',
      'no STB mutation path confirmed',
      'no publishing path confirmed',
    ],
    blockedChecks: [
      'compliance evaluation is not enabled',
      'compliance records are not persisted',
      'provider output is not inspected directly',
    ],
    evidenceReferencesRequiredBeforeFutureProviderEnablement: [
      'credential-isolation-plan-ref',
      'prompt-review-policy-ref',
      'artifact-sandbox-handoff-plan-ref',
      'output-redaction-policy-ref',
      'provider-boundary-plan-ref',
      'audit-reference-policy-ref',
      'rollback-cleanup-policy-ref',
    ],
    disallowedComplianceEvidenceSources: [
      'raw provider responses',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'unredacted logs',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'generated media files',
      'arbitrary shell output',
    ],
    operatorReviewGates: ['approved checklist schema', 'approved evidence reference policy', 'approved operator review gate', 'approved rollback linkage'],
    auditRequirements: [
      'Audit output must remain reference-only.',
      'No compliance record may be persisted in this phase.',
      'Any future review state must remain redacted and immutable.',
    ],
    blockers: ['No approved checklist schema', 'No evidence reference policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the checklist reference model and operator review gates before any compliance evaluation exists.',
    safety: {
      readOnly: true,
      complianceChecklistDesignOnly: true,
      complianceEvaluationEnabled: false,
      complianceRecordPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      credentialAccessEnabled: false,
      auditPersistenceEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'brand-compliance-compliance-checklist',
    providerClass: 'brand-compliance',
    checklistCategory: 'brand-compliance-checklist',
    status: 'blocked',
    purpose: 'Define a future compliance checklist for brand-compliance providers without enabling compliance evaluation or persistence.',
    requiredChecks: [
      'credential isolation plan reviewed',
      'prompt review policy reviewed',
      'artifact sandbox handoff plan reviewed',
      'output redaction policy reviewed',
      'provider boundary plan reviewed',
      'operator approval gate defined',
      'audit reference policy defined',
      'rollback/cleanup policy linked',
      'no STB mutation path confirmed',
      'no publishing path confirmed',
    ],
    blockedChecks: [
      'compliance evaluation is not enabled',
      'compliance records are not persisted',
      'provider output is not inspected directly',
    ],
    evidenceReferencesRequiredBeforeFutureProviderEnablement: [
      'credential-isolation-plan-ref',
      'prompt-review-policy-ref',
      'artifact-sandbox-handoff-plan-ref',
      'output-redaction-policy-ref',
      'provider-boundary-plan-ref',
      'audit-reference-policy-ref',
      'rollback-cleanup-policy-ref',
    ],
    disallowedComplianceEvidenceSources: [
      'raw provider responses',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'unredacted logs',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'generated media files',
      'arbitrary shell output',
    ],
    operatorReviewGates: ['approved checklist schema', 'approved evidence reference policy', 'approved operator review gate', 'approved rollback linkage'],
    auditRequirements: [
      'Audit output must remain reference-only.',
      'No compliance record may be persisted in this phase.',
      'Any future review state must remain redacted and immutable.',
    ],
    blockers: ['No approved checklist schema', 'No evidence reference policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the checklist reference model and operator review gates before any compliance evaluation exists.',
    safety: {
      readOnly: true,
      complianceChecklistDesignOnly: true,
      complianceEvaluationEnabled: false,
      complianceRecordPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      credentialAccessEnabled: false,
      auditPersistenceEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
];

export function readVideoDesignProviderComplianceChecklistPlans(): BrainCoreVideoDesignProviderComplianceChecklistPlanResponse {
  return {
    id: 'video-orchestrator-design-provider-compliance-checklist-plan',
    status: 'blocked',
    phase: 'design-provider-compliance-checklist-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      checklistCount: checklists.length,
      blockedCount: checklists.filter((checklist) => checklist.status === 'blocked').length,
      requiredCheckCount: checklists.reduce((count, checklist) => count + checklist.requiredChecks.length, 0),
      passedCheckCount: 0,
      persistedComplianceRecordCount: 0,
      providerCallCount: 0,
      auditPersistedCount: 0,
    },
    checklists,
    safety: {
      readOnly: true,
      complianceChecklistDesignOnly: true,
      complianceEvaluationEnabled: false,
      complianceRecordPersistenceEnabled: false,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      credentialAccessEnabled: false,
      auditPersistenceEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved checklist schema', 'No evidence reference policy', 'No operator approval workflow'],
    nextSafeStep: 'Design the checklist reference model and operator review gates before any compliance evaluation exists.',
  };
}

export function readVideoDesignProviderComplianceChecklistPlan(
  id: string,
): BrainCoreVideoDesignProviderComplianceChecklistPlan | undefined {
  return checklists.find((checklist) => checklist.id === id || checklist.providerClass === id);
}
