import type {
  BrainCoreVideoDesignProviderBoundaryPlan,
  BrainCoreVideoDesignProviderBoundaryPlanResponse,
} from '../types/api.js';

const providerBoundaries: BrainCoreVideoDesignProviderBoundaryPlan[] = [
  {
    id: 'design-provider-boundary-image-generation',
    providerClass: 'image-generation',
    status: 'blocked',
    purpose: 'Define future image-generation provider isolation before any thumbnail or scene asset generation is enabled.',
    allowedFutureInputs: ['designPlanId', 'thumbnailPlanId', 'operatorApprovedPromptRef', 'artifactSandboxRef', 'policyVersion'],
    disallowedInputs: ['raw secrets', 'OAuth tokens', 'arbitrary shell text', 'unapproved file paths', 'Mind vault paths', 'STB artifact paths'],
    outputPolicy: {
      allowedFutureOutputs: ['providerRequestPreview', 'redactedPromptPreview', 'artifactManifestPlaceholder', 'auditReferencePlaceholder'],
      disallowedOutputs: ['generated image bytes', 'published media', 'filesystem paths outside sandbox', 'credentials', 'raw provider logs'],
      retention: 'No output retention in this phase; future retention requires artifact sandbox and audit policy approval.',
    },
    requiredGates: ['artifact sandbox policy approved', 'operator prompt review approved', 'provider credential isolation approved', 'audit trail persistence approved'],
    safety: {
      readOnly: true,
      boundaryDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      promptGenerationEnabled: false,
      imageGenerationEnabled: false,
      artifactPersistenceEnabled: false,
      credentialAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved provider credential isolation', 'No artifact sandbox execution boundary', 'No prompt approval workflow', 'No audit persistence'],
    nextSafeStep: 'Design prompt-review and artifact sandbox handoff before configuring an image provider.',
  },
  {
    id: 'design-provider-boundary-layout-rendering',
    providerClass: 'layout-rendering',
    status: 'blocked',
    purpose: 'Define future layout/rendering provider boundaries for title cards, overlays, and platform derivatives without rendering.',
    allowedFutureInputs: ['designSpecId', 'assemblyPlanId', 'platformLayoutPolicyRef', 'artifactSandboxRef', 'operatorApprovalRef'],
    disallowedInputs: ['arbitrary render scripts', 'source repo write paths', 'Mind vault paths', 'platform API credentials', 'STB mutation targets'],
    outputPolicy: {
      allowedFutureOutputs: ['renderPlanPreview', 'layoutManifestPlaceholder', 'safeAreaReportPlaceholder', 'auditReferencePlaceholder'],
      disallowedOutputs: ['rendered media files', 'filesystem writes', 'platform uploads', 'STB mutations', 'unredacted runtime logs'],
      retention: 'Report-only until render/export policy, artifact policy, and sandbox lifecycle are approved.',
    },
    requiredGates: ['render/export policy approved', 'artifact output policy approved', 'sandbox teardown policy approved', 'STB protection policy approved'],
    safety: {
      readOnly: true,
      boundaryDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      promptGenerationEnabled: false,
      imageGenerationEnabled: false,
      artifactPersistenceEnabled: false,
      credentialAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved render/export execution path', 'No artifact output path policy', 'No sandbox lifecycle approval'],
    nextSafeStep: 'Keep layout rendering as a report-only boundary until render/export and artifact policies are approved.',
  },
  {
    id: 'design-provider-boundary-brand-compliance',
    providerClass: 'brand-compliance',
    status: 'blocked',
    purpose: 'Define future brand/compliance checks for design assets without calling providers or persisting audit output.',
    allowedFutureInputs: ['metadataPlanId', 'platformPolicyRef', 'thumbnailPlanId', 'complianceChecklistRef', 'operatorReviewPacketRef'],
    disallowedInputs: ['raw account data', 'Stripe or financial records', 'platform API tokens', 'unredacted analytics exports', 'private notes'],
    outputPolicy: {
      allowedFutureOutputs: ['compliancePreview', 'policyGapSummary', 'redactedReviewPacketPlaceholder', 'auditReferencePlaceholder'],
      disallowedOutputs: ['platform submissions', 'financial data', 'credential material', 'published metadata', 'Mind writes'],
      retention: 'No persistence until immutable audit trail and compliance evidence packet are approved.',
    },
    requiredGates: ['platform policy approved', 'compliance packet policy approved', 'operator review approved', 'audit retention policy approved'],
    safety: {
      readOnly: true,
      boundaryDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      promptGenerationEnabled: false,
      imageGenerationEnabled: false,
      artifactPersistenceEnabled: false,
      credentialAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No compliance evidence packet implementation', 'No platform policy enforcement', 'No immutable audit persistence'],
    nextSafeStep: 'Design compliance review packet shape before enabling any provider integration.',
  },
];

export function readVideoDesignProviderBoundaryPlans(): BrainCoreVideoDesignProviderBoundaryPlanResponse {
  return {
    id: 'video-orchestrator-design-provider-boundary-plan',
    status: 'blocked',
    phase: 'design-provider-boundary-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      boundaryCount: providerBoundaries.length,
      blockedCount: providerBoundaries.filter((boundary) => boundary.status === 'blocked').length,
      providerConfiguredCount: 0,
      providerCallCount: 0,
      artifactPersistenceCount: 0,
    },
    boundaries: providerBoundaries,
    safety: {
      readOnly: true,
      boundaryDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      promptGenerationEnabled: false,
      imageGenerationEnabled: false,
      artifactPersistenceEnabled: false,
      credentialAccessEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved provider credential isolation', 'No artifact sandbox boundary', 'No prompt review workflow', 'No immutable audit persistence'],
    nextSafeStep: 'Create provider credential isolation and prompt review plans before configuring any design provider.',
  };
}

export function readVideoDesignProviderBoundaryPlan(id: string): BrainCoreVideoDesignProviderBoundaryPlan | undefined {
  return providerBoundaries.find((boundary) => boundary.id === id || boundary.providerClass === id);
}
