import type {
  BrainCoreVideoVoiceoverSegment,
  BrainCoreVideoVoiceoverPlan,
  BrainCoreVideoVoiceoverPlanListResponse,
  BrainCoreVideoVoiceoverPlanDetailResponse,
} from '../types/api.js';

interface VoiceoverPlanFixture {
  intakePlanId: string;
  scriptPlanId: string;
  storySlug: string;
  title: string;
  estimatedDurationMinutes: number;
  segments: BrainCoreVideoVoiceoverSegment[];
}

const voiceoverPlanFixtures: VoiceoverPlanFixture[] = [
  {
    intakePlanId: 'plan-intake-fixture-052',
    scriptPlanId: 'script-plan-plan-intake-fixture-052',
    storySlug: '052-2kings-widow-oil-30m',
    title: 'The Widow\'s Oil | Bible Bedtime Story',
    estimatedDurationMinutes: 30,
    segments: [
      {
        id: 'seg-052-001-intro',
        scriptSectionId: 'script-section-intro',
        sequence: 1,
        label: 'Introduction',
        kind: 'intro',
        status: 'planned',
        placeholder: 'Intro narration placeholder for validation only.',
        estimatedDurationSeconds: 45,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['gentle-greeting', 'story-setup'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-052-002-body',
        scriptSectionId: 'script-section-body',
        sequence: 2,
        label: 'Story Body',
        kind: 'body',
        status: 'planned',
        placeholder: 'Body narration placeholder for validation only.',
        estimatedDurationSeconds: 1200,
        voiceRequirements: {
          tone: 'story',
          pacing: 'medium',
          emphasis: ['character-voices', 'dialog-variety'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-052-003-passage',
        scriptSectionId: 'script-section-passage',
        sequence: 3,
        label: 'Scripture Passage',
        kind: 'passage',
        status: 'planned',
        placeholder: 'Passage narration placeholder for validation only.',
        estimatedDurationSeconds: 60,
        voiceRequirements: {
          tone: 'educational',
          pacing: 'slow',
          emphasis: ['scripture-emphasis', 'clarity'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-052-004-application',
        scriptSectionId: 'script-section-application',
        sequence: 4,
        label: 'Life Application',
        kind: 'application',
        status: 'planned',
        placeholder: 'Application narration placeholder for validation only.',
        estimatedDurationSeconds: 90,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['reflective-pause', 'gentle-guidance'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-052-005-outro',
        scriptSectionId: 'script-section-outro',
        sequence: 5,
        label: 'Outro/Closing',
        kind: 'outro',
        status: 'planned',
        placeholder: 'Outro narration placeholder for validation only.',
        estimatedDurationSeconds: 30,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'slow',
          emphasis: ['blessing', 'peaceful-close'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
    ],
  },
  {
    intakePlanId: 'plan-intake-fixture-053',
    scriptPlanId: 'script-plan-plan-intake-fixture-053',
    storySlug: '053-2kings-elisha-drown-30m',
    title: 'Elisha and the Drowned Axe | Bible Bedtime Story',
    estimatedDurationMinutes: 30,
    segments: [
      {
        id: 'seg-053-001-intro',
        scriptSectionId: 'script-section-intro',
        sequence: 1,
        label: 'Introduction',
        kind: 'intro',
        status: 'planned',
        placeholder: 'Intro narration placeholder for validation only.',
        estimatedDurationSeconds: 45,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['gentle-greeting', 'story-setup'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-053-002-body',
        scriptSectionId: 'script-section-body',
        sequence: 2,
        label: 'Story Body',
        kind: 'body',
        status: 'planned',
        placeholder: 'Body narration placeholder for validation only.',
        estimatedDurationSeconds: 1200,
        voiceRequirements: {
          tone: 'story',
          pacing: 'medium',
          emphasis: ['character-voices', 'miracle-emphasis'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-053-003-passage',
        scriptSectionId: 'script-section-passage',
        sequence: 3,
        label: 'Scripture Passage',
        kind: 'passage',
        status: 'planned',
        placeholder: 'Passage narration placeholder for validation only.',
        estimatedDurationSeconds: 60,
        voiceRequirements: {
          tone: 'educational',
          pacing: 'slow',
          emphasis: ['scripture-emphasis', 'clarity'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-053-004-outro',
        scriptSectionId: 'script-section-outro',
        sequence: 4,
        label: 'Outro/Closing',
        kind: 'outro',
        status: 'planned',
        placeholder: 'Outro narration placeholder for validation only.',
        estimatedDurationSeconds: 30,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'slow',
          emphasis: ['blessing', 'peaceful-close'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
    ],
  },
  {
    intakePlanId: 'plan-intake-fixture-054',
    scriptPlanId: 'script-plan-plan-intake-fixture-054',
    storySlug: '054-2kings-elisha-leprosy-30m',
    title: 'Naaman\'s Healing | Bible Bedtime Story',
    estimatedDurationMinutes: 30,
    segments: [
      {
        id: 'seg-054-001-intro',
        scriptSectionId: 'script-section-intro',
        sequence: 1,
        label: 'Introduction',
        kind: 'intro',
        status: 'planned',
        placeholder: 'Intro narration placeholder for validation only.',
        estimatedDurationSeconds: 45,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['gentle-greeting', 'story-setup'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-054-002-body',
        scriptSectionId: 'script-section-body',
        sequence: 2,
        label: 'Story Body',
        kind: 'body',
        status: 'planned',
        placeholder: 'Body narration placeholder for validation only.',
        estimatedDurationSeconds: 1200,
        voiceRequirements: {
          tone: 'story',
          pacing: 'medium',
          emphasis: ['character-voices', 'healing-moment'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-054-003-passage',
        scriptSectionId: 'script-section-passage',
        sequence: 3,
        label: 'Scripture Passage',
        kind: 'passage',
        status: 'planned',
        placeholder: 'Passage narration placeholder for validation only.',
        estimatedDurationSeconds: 60,
        voiceRequirements: {
          tone: 'educational',
          pacing: 'slow',
          emphasis: ['scripture-emphasis', 'clarity'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-054-004-outro',
        scriptSectionId: 'script-section-outro',
        sequence: 4,
        label: 'Outro/Closing',
        kind: 'outro',
        status: 'planned',
        placeholder: 'Outro narration placeholder for validation only.',
        estimatedDurationSeconds: 30,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'slow',
          emphasis: ['blessing', 'peaceful-close'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
    ],
  },
  {
    intakePlanId: 'plan-intake-fixture-055',
    scriptPlanId: 'script-plan-plan-intake-fixture-055',
    storySlug: '055-2kings-elisha-vision-30m',
    title: 'The Army of Heaven | Bible Bedtime Story',
    estimatedDurationMinutes: 30,
    segments: [
      {
        id: 'seg-055-001-intro',
        scriptSectionId: 'script-section-intro',
        sequence: 1,
        label: 'Introduction',
        kind: 'intro',
        status: 'planned',
        placeholder: 'Intro narration placeholder for validation only.',
        estimatedDurationSeconds: 45,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['gentle-greeting', 'story-setup'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-055-002-body',
        scriptSectionId: 'script-section-body',
        sequence: 2,
        label: 'Story Body',
        kind: 'body',
        status: 'planned',
        placeholder: 'Body narration placeholder for validation only.',
        estimatedDurationSeconds: 1200,
        voiceRequirements: {
          tone: 'story',
          pacing: 'medium',
          emphasis: ['character-voices', 'wonder-emphasis'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-055-003-outro',
        scriptSectionId: 'script-section-outro',
        sequence: 3,
        label: 'Outro/Closing',
        kind: 'outro',
        status: 'planned',
        placeholder: 'Outro narration placeholder for validation only.',
        estimatedDurationSeconds: 30,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'slow',
          emphasis: ['blessing', 'peaceful-close'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
    ],
  },
  {
    intakePlanId: 'plan-intake-fixture-056',
    scriptPlanId: 'script-plan-plan-intake-fixture-056',
    storySlug: '056-luke-jesus-asks-faith-30m',
    title: 'Jesus and the Storm | Bible Bedtime Story',
    estimatedDurationMinutes: 30,
    segments: [
      {
        id: 'seg-056-001-intro',
        scriptSectionId: 'script-section-intro',
        sequence: 1,
        label: 'Introduction',
        kind: 'intro',
        status: 'planned',
        placeholder: 'Intro narration placeholder for validation only.',
        estimatedDurationSeconds: 45,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'measured',
          emphasis: ['gentle-greeting', 'story-setup'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-056-002-body',
        scriptSectionId: 'script-section-body',
        sequence: 2,
        label: 'Story Body',
        kind: 'body',
        status: 'planned',
        placeholder: 'Body narration placeholder for validation only.',
        estimatedDurationSeconds: 1200,
        voiceRequirements: {
          tone: 'story',
          pacing: 'medium',
          emphasis: ['drama-moment', 'storm-sound-effects'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-056-003-passage',
        scriptSectionId: 'script-section-passage',
        sequence: 3,
        label: 'Scripture Passage',
        kind: 'passage',
        status: 'planned',
        placeholder: 'Passage narration placeholder for validation only.',
        estimatedDurationSeconds: 60,
        voiceRequirements: {
          tone: 'educational',
          pacing: 'slow',
          emphasis: ['scripture-emphasis', 'clarity'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
      {
        id: 'seg-056-004-outro',
        scriptSectionId: 'script-section-outro',
        sequence: 4,
        label: 'Outro/Closing',
        kind: 'outro',
        status: 'planned',
        placeholder: 'Outro narration placeholder for validation only.',
        estimatedDurationSeconds: 30,
        voiceRequirements: {
          tone: 'calm',
          pacing: 'slow',
          emphasis: ['blessing', 'peaceful-close'],
        },
        pronunciationNotes: ['placeholder for validation only'],
        blockers: ['TTS/audio generation not yet implemented'],
        safety: {
          readOnly: true,
          generatesAudio: false,
          callsTts: false,
          callsExternalAI: false,
          writesFiles: false,
          publishesContent: false,
          writesToMind: false,
        },
      },
    ],
  },
];

function generateVoiceoverPlan(fixture: VoiceoverPlanFixture): BrainCoreVideoVoiceoverPlan {
  const plannedCount = fixture.segments.filter(s => s.status === 'planned').length;
  const blockedCount = fixture.segments.filter(s => s.status === 'blocked').length;
  const totalDurationSeconds = fixture.segments.reduce((sum, s) => sum + s.estimatedDurationSeconds, 0);
  const totalDurationMinutes = Math.round(totalDurationSeconds / 60);

  return {
    id: `voiceover-plan-${fixture.scriptPlanId}`,
    scriptPlanId: fixture.scriptPlanId,
    intakePlanId: fixture.intakePlanId,
    projectId: 'says-the-bible-video',
    title: fixture.title,
    generatedAt: new Date().toISOString(),
    status: blockedCount > 0 ? 'blocked' : 'preview-ready',
    segments: fixture.segments,
    summary: {
      totalSegments: fixture.segments.length,
      plannedCount,
      blockedCount,
      estimatedDurationSeconds: totalDurationSeconds,
      estimatedDurationMinutes: totalDurationMinutes,
    },
    blockers: [
      'TTS/audio generation not yet implemented',
      'Manual recording fallback not configured',
      'Audio file writing not enabled',
    ],
    nextSafeStep: 'Implement TTS/audio generation module or configure manual recording interface',
    safety: {
      readOnly: true,
      executesStb: false,
      executesVideo: false,
      generatesAudio: false,
      callsTts: false,
      callsExternalAI: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
    },
  };
}

export function readVideoVoiceoverPlans(): BrainCoreVideoVoiceoverPlanListResponse {
  const plans = voiceoverPlanFixtures.map(generateVoiceoverPlan);
  const previewReadyCount = plans.filter(p => p.status === 'preview-ready').length;
  const blockedCount = plans.filter(p => p.status === 'blocked').length;
  const totalSegments = plans.reduce((sum, p) => sum + p.summary.totalSegments, 0);
  const estimatedDurationMinutes = plans.reduce((sum, p) => sum + p.summary.estimatedDurationMinutes, 0);

  return {
    id: 'video-orchestrator-voiceover-plan',
    generatedAt: new Date().toISOString(),
    version: '1.0',
    plans,
    summary: {
      total: plans.length,
      previewReadyCount,
      blockedCount,
      totalSegments,
      estimatedDurationMinutes,
    },
    safety: {
      readOnly: true,
      executesStb: false,
      executesVideo: false,
      generatesAudio: false,
      callsTts: false,
      callsExternalAI: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
    },
  };
}

export function readVideoVoiceoverPlan(scriptPlanId: string): BrainCoreVideoVoiceoverPlanDetailResponse | undefined {
  const fixture = voiceoverPlanFixtures.find(f => f.scriptPlanId === scriptPlanId);
  if (!fixture) return undefined;

  const plan = generateVoiceoverPlan(fixture);

  return {
    id: plan.id,
    generatedAt: new Date().toISOString(),
    version: '1.0',
    plan,
    upstream: {
      scriptPlanId: fixture.scriptPlanId,
      intakePlanId: fixture.intakePlanId,
    },
    nextSafeStep: 'TTS/audio generation required to produce narration audio; otherwise manual recording needed',
    safety: {
      readOnly: true,
      executesStb: false,
      executesVideo: false,
      generatesAudio: false,
      callsTts: false,
      callsExternalAI: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
    },
  };
}
