import type {
  BrainCoreVideoProviderOutputRedactionPolicyPlan,
  BrainCoreVideoProviderOutputRedactionPolicyPlanResponse,
} from '../types/api.js';

const policies: BrainCoreVideoProviderOutputRedactionPolicyPlan[] = [
  {
    id: 'image-generation-output-redaction',
    providerClass: 'image-generation',
    outputCategory: 'image-generation-output',
    status: 'blocked',
    purpose: 'Define a future redaction boundary for image-generation outputs without exposing raw payloads or creating redacted manifests.',
    allowedFutureOutputSummaryFields: ['sourcePlanId', 'providerClass', 'outputCategory', 'redactedSummary', 'policyVersion'],
    disallowedRawOutputFields: [
      'raw provider response',
      'raw generated files',
      'raw prompt text',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'provider request IDs that expose account data',
      'unredacted logs',
      'arbitrary shell text',
    ],
    redactionRules: [
      'replace credential-like values with [REDACTED]',
      'omit raw provider payloads',
      'omit absolute local paths',
      'omit Mind vault paths',
      'omit STB artifact paths',
      'omit account identifiers',
      'keep only stable internal references',
      'include policy version',
      'include redaction timestamp placeholder',
      'include audit reference placeholder',
    ],
    proposedRedactedManifestFields: [
      'redactedArtifactId',
      'providerClass',
      'sourcePlanId',
      'redactionPolicyId',
      'artifactSandboxHandoffPlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'redactedSummary',
      'omittedFieldCount',
      'policyVersion',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
    ],
    auditReferenceRequirements: [
      'Audit references must be redacted and stable.',
      'No raw provider response or payload may be persisted.',
      'Any future redaction record must remain reference-only.',
    ],
    operatorReviewGates: [
      'approved redaction policy schema',
      'approved sandbox handoff policy',
      'approved prompt review policy',
      'approved operator review gate',
    ],
    blockers: ['No approved redaction policy schema', 'No provider output reference model', 'No operator approval workflow'],
    nextSafeStep: 'Design the redaction manifest and internal reference rules before any provider output is summarized.',
    safety: {
      readOnly: true,
      redactionPolicyDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      redactedManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      auditPersistenceEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'layout-rendering-output-redaction',
    providerClass: 'layout-rendering',
    outputCategory: 'layout-rendering-output',
    status: 'blocked',
    purpose: 'Define a future redaction boundary for layout-rendering outputs without exposing raw files or platform upload data.',
    allowedFutureOutputSummaryFields: ['sourcePlanId', 'providerClass', 'outputCategory', 'redactedSummary', 'policyVersion'],
    disallowedRawOutputFields: [
      'raw provider response',
      'raw generated files',
      'raw prompt text',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'provider request IDs that expose account data',
      'unredacted logs',
      'arbitrary shell text',
    ],
    redactionRules: [
      'replace credential-like values with [REDACTED]',
      'omit raw provider payloads',
      'omit absolute local paths',
      'omit Mind vault paths',
      'omit STB artifact paths',
      'omit account identifiers',
      'keep only stable internal references',
      'include policy version',
      'include redaction timestamp placeholder',
      'include audit reference placeholder',
    ],
    proposedRedactedManifestFields: [
      'redactedArtifactId',
      'providerClass',
      'sourcePlanId',
      'redactionPolicyId',
      'artifactSandboxHandoffPlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'redactedSummary',
      'omittedFieldCount',
      'policyVersion',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
    ],
    auditReferenceRequirements: [
      'Audit references must be redacted and stable.',
      'No raw provider response or payload may be persisted.',
      'Any future redaction record must remain reference-only.',
    ],
    operatorReviewGates: [
      'approved redaction policy schema',
      'approved sandbox handoff policy',
      'approved prompt review policy',
      'approved operator review gate',
    ],
    blockers: ['No approved redaction policy schema', 'No provider output reference model', 'No operator approval workflow'],
    nextSafeStep: 'Design the redaction manifest and internal reference rules before any layout output is summarized.',
    safety: {
      readOnly: true,
      redactionPolicyDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      redactedManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      auditPersistenceEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
  {
    id: 'brand-compliance-output-redaction',
    providerClass: 'brand-compliance',
    outputCategory: 'brand-compliance-output',
    status: 'blocked',
    purpose: 'Define a future redaction boundary for brand-compliance outputs without exposing raw logs or account data.',
    allowedFutureOutputSummaryFields: ['sourcePlanId', 'providerClass', 'outputCategory', 'redactedSummary', 'policyVersion'],
    disallowedRawOutputFields: [
      'raw provider response',
      'raw generated files',
      'raw prompt text',
      'raw credentials',
      'API keys',
      'OAuth tokens',
      'private keys',
      '.env dumps',
      'filesystem paths outside approved sandbox',
      'Mind vault paths',
      'STB artifact paths',
      'platform upload payloads',
      'provider request IDs that expose account data',
      'unredacted logs',
      'arbitrary shell text',
    ],
    redactionRules: [
      'replace credential-like values with [REDACTED]',
      'omit raw provider payloads',
      'omit absolute local paths',
      'omit Mind vault paths',
      'omit STB artifact paths',
      'omit account identifiers',
      'keep only stable internal references',
      'include policy version',
      'include redaction timestamp placeholder',
      'include audit reference placeholder',
    ],
    proposedRedactedManifestFields: [
      'redactedArtifactId',
      'providerClass',
      'sourcePlanId',
      'redactionPolicyId',
      'artifactSandboxHandoffPlanId',
      'promptReviewPolicyId',
      'credentialIsolationPlanId',
      'redactedSummary',
      'omittedFieldCount',
      'policyVersion',
      'auditRefPlaceholder',
      'createdAtPlaceholder',
    ],
    auditReferenceRequirements: [
      'Audit references must be redacted and stable.',
      'No raw provider response or payload may be persisted.',
      'Any future redaction record must remain reference-only.',
    ],
    operatorReviewGates: [
      'approved redaction policy schema',
      'approved sandbox handoff policy',
      'approved prompt review policy',
      'approved operator review gate',
    ],
    blockers: ['No approved redaction policy schema', 'No provider output reference model', 'No operator approval workflow'],
    nextSafeStep: 'Design the redaction manifest and internal reference rules before any brand-compliance output is summarized.',
    safety: {
      readOnly: true,
      redactionPolicyDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      redactedManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      auditPersistenceEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
  },
];

export function readVideoProviderOutputRedactionPolicyPlans(): BrainCoreVideoProviderOutputRedactionPolicyPlanResponse {
  return {
    id: 'video-orchestrator-provider-output-redaction-policy-plan',
    status: 'blocked',
    phase: 'provider-output-redaction-policy-plan-read-only',
    generatedAt: new Date().toISOString(),
    summary: {
      policyCount: policies.length,
      blockedCount: policies.filter((policy) => policy.status === 'blocked').length,
      redactedManifestCreatedCount: 0,
      rawOutputAccessCount: 0,
      providerCallCount: 0,
      artifactPersistedCount: 0,
      auditPersistedCount: 0,
    },
    policies,
    safety: {
      readOnly: true,
      redactionPolicyDesignOnly: true,
      providerConfigured: false,
      providerCallsEnabled: false,
      rawProviderOutputAccessEnabled: false,
      redactedManifestCreationEnabled: false,
      artifactPersistenceEnabled: false,
      auditPersistenceEnabled: false,
      credentialAccessEnabled: false,
      rawCredentialDisplayEnabled: false,
      filesystemAccessEnabled: false,
      networkAccessEnabled: false,
      writesFiles: false,
      publishesContent: false,
      writesToMind: false,
      executesVideo: false,
    },
    blockers: ['No approved redaction policy schema', 'No provider output reference model', 'No operator approval workflow'],
    nextSafeStep: 'Design the redaction manifest and internal reference rules before any provider output is summarized.',
  };
}

export function readVideoProviderOutputRedactionPolicyPlan(
  id: string,
): BrainCoreVideoProviderOutputRedactionPolicyPlan | undefined {
  return policies.find((policy) => policy.id === id || policy.providerClass === id);
}
