import assert from 'node:assert/strict';
import test from 'node:test';
import { AGENT_MODE_PRINCIPAL_RESOURCES, AGENT_MODE_TIER_POLICY_VERSION, admitCodexResource, admitManualModelOverride, selectAgentModeAfterEscalationRequest, selectAgentModeExecutionModel, selectAgentModeModel, type AgentModePolicyInput, type RouteEvidence } from '../agent-mode/model-tier-policy.js';
import type { AdmittedModelRef } from '../agent-mode/model-gateway.js';

const now = '2026-09-09T12:00:00.000Z';
const refs: AdmittedModelRef[] = ['agent-mode/minimax-m2.5', 'agent-mode/glm-5', 'agent-mode/claude-opus-4.6'];
function evidence(overrides: Partial<RouteEvidence> = {}): Readonly<Record<AdmittedModelRef, RouteEvidence>> {
  return Object.fromEntries(refs.map((modelRef) => [modelRef, { modelRef, routeKind: modelRef === 'agent-mode/claude-opus-4.6' ? 'inference-profile' : 'direct', routeId: modelRef === 'agent-mode/claude-opus-4.6' ? 'us.anthropic.claude-opus-4-6-v1' : modelRef === 'agent-mode/glm-5' ? 'zai.glm-5' : 'minimax.minimax-m2.5', state: 'healthy', accessState: 'verified', checkedAt: '2026-09-09T11:00:00.000Z', freshUntil: '2026-09-09T13:00:00.000Z', evidenceVersion: 'k1.1-fixture', ...overrides }])) as Readonly<Record<AdmittedModelRef, RouteEvidence>>;
}
function input(overrides: Partial<AgentModePolicyInput> = {}): AgentModePolicyInput {
  return { taskClass: 'worker', requiredContextTokens: 1000, requiredOutputTokens: 1000, budgetScopeId: 'root-1', rootBudgetScopeId: 'root-1', maxDollars: 10, inputTokens: 1000, outputTokens: 1000, now, routeEvidence: evidence(), selectionMode: 'auto', phase: 'root', maxEscalationDepth: 2, ...overrides };
}

test('selects exact worker route initially', () => { const d = selectAgentModeModel(input()); assert.equal(d.ok, true); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); assert.equal(d.tier, 'worker'); assert.equal(d.route?.routeId, 'minimax.minimax-m2.5'); });
test('manual model override is admitted only through the fixed policy', () => { assert.deepEqual(admitManualModelOverride('agent-mode/glm-5'), { ok: true, policyVersion: AGENT_MODE_TIER_POLICY_VERSION, modelRef: 'agent-mode/glm-5', tier: 'senior' }); assert.equal(admitManualModelOverride('ollama/qwen').ok, false); });

test('Auto root worker class always begins with MiniMax scout', () => { const d = selectAgentModeModel(input({ taskClass: 'worker' })); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('Auto root senior class always begins with MiniMax scout', () => { const d = selectAgentModeModel(input({ taskClass: 'senior' })); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('Auto root principal class always begins with MiniMax scout', () => { const d = selectAgentModeModel(input({ taskClass: 'principal' })); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('bounded Auto task admits a MiniMax completion shape', () => { const d = selectAgentModeModel(input({ requiredContextTokens: 2_000, requiredOutputTokens: 512 })); assert.equal(d.ok, true); assert.equal(d.tier, 'worker'); assert.equal(d.reason, 'initial_selection'); });
test('structured senior escalation request is policy-interpreted, not model-authorized', () => { const d = selectAgentModeModel(input({ taskClass: 'senior', previousAttempt: { tier: 'worker', outcome: 'quality_failure' } })); assert.equal(d.modelRef, 'agent-mode/glm-5'); assert.equal(d.reason, 'validated_reasoning_failure'); });
test('structured principal escalation request reaches Opus cost gate', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'senior', outcome: 'validation_failure' } })); assert.equal(d.modelRef, 'agent-mode/claude-opus-4.6'); assert.equal(d.reason, 'cost_unknown'); });
test('Brain ignores an untrusted requested tier and derives escalation from prior tier', () => { const d = selectAgentModeAfterEscalationRequest(input(), { kind: 'escalation_requested', fromTier: 'worker', requestedTier: 'principal', reason: 'task_class_requires_principal', source: 'model-untrusted' }); assert.equal(d.modelRef, 'agent-mode/glm-5'); });
test('validated worker quality failure escalates to GLM', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'worker', outcome: 'quality_failure' } })); assert.equal(d.tier, 'senior'); assert.equal(d.modelRef, 'agent-mode/glm-5'); });
test('validated GLM failure escalates to Opus but remains fail closed on price', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'senior', outcome: 'validation_failure' } })); assert.equal(d.tier, 'principal'); assert.equal(d.reason, 'cost_unknown'); });
test('provider timeout does not escalate reasoning tier', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'worker', outcome: 'provider_failure' } })); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); assert.equal(d.tier, 'worker'); });
test('completed planning work package gets fresh execution admission', () => { const d = selectAgentModeExecutionModel(input({ taskClass: 'worker', previousAttempt: { tier: 'worker', outcome: 'completed' } })); assert.equal(d.ok, true); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('execution worker package selects MiniMax', () => { const d = selectAgentModeExecutionModel(input({ taskClass: 'worker' })); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('execution senior package selects GLM', () => { const d = selectAgentModeExecutionModel(input({ taskClass: 'senior', requiredContextTokens: 197_000 })); assert.equal(d.modelRef, 'agent-mode/glm-5'); });
test('Codex Astra is a separate fixture-only principal resource', () => { assert.equal(AGENT_MODE_PRINCIPAL_RESOURCES.codexAstra.resource, 'codex-subscription'); assert.equal(AGENT_MODE_PRINCIPAL_RESOURCES.codexAstra.availability, 'fixture-only'); });
test('unknown Codex quota keeps Astra/Luna-style automatic resources gated', () => { const d = admitCodexResource({ mode: 'automatic', estimatedTokens: 1, now, evidence: { state: 'unknown', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }); assert.equal(d.ok, false); });
test('maximum escalation depth prevents a principal loop', () => { const d = selectAgentModeModel(input({ maxEscalationDepth: 2, previousAttempt: { tier: 'principal', outcome: 'quality_failure' } })); assert.equal(d.ok, false); assert.equal(d.reason, 'max_escalation_depth'); });
test('root budget scope mismatch denies escalation', () => { const d = selectAgentModeModel(input({ parentBudgetScopeId: 'child-budget', previousAttempt: { tier: 'worker', outcome: 'quality_failure' } })); assert.equal(d.ok, false); assert.equal(d.reason, 'invalid_scope'); });
test('manual MiniMax selection is direct and policy-gated', () => { const d = selectAgentModeModel(input({ selectionMode: 'manual', manualModelRef: 'agent-mode/minimax-m2.5', taskClass: 'principal' })); assert.equal(d.ok, true); assert.equal(d.modelRef, 'agent-mode/minimax-m2.5'); });
test('manual GLM selection is direct and policy-gated', () => { const d = selectAgentModeModel(input({ selectionMode: 'manual', manualModelRef: 'agent-mode/glm-5', taskClass: 'worker' })); assert.equal(d.ok, true); assert.equal(d.modelRef, 'agent-mode/glm-5'); });
test('manual Opus selection remains fail closed without verified pricing', () => { const d = selectAgentModeModel(input({ selectionMode: 'manual', manualModelRef: 'agent-mode/claude-opus-4.6' })); assert.equal(d.ok, false); assert.equal(d.reason, 'cost_unknown'); });
test('policy selection is offline and does not call the network', () => { const originalFetch = globalThis.fetch; let calls = 0; globalThis.fetch = (async () => { calls += 1; throw new Error('network must not be called'); }) as typeof fetch; try { selectAgentModeModel(input()); } finally { globalThis.fetch = originalFetch; } assert.equal(calls, 0); });

test('execution senior class selects GLM after Auto scout', () => { const d = selectAgentModeModel(input({ taskClass: 'senior', phase: 'execution' })); assert.equal(d.modelRef, 'agent-mode/glm-5'); assert.equal(d.tier, 'senior'); });
test('execution principal class selects principal reference but gates unknown Opus pricing', () => { const d = selectAgentModeModel(input({ taskClass: 'principal', phase: 'execution' })); assert.equal(d.reason, 'cost_unknown'); assert.equal(d.modelRef, 'agent-mode/claude-opus-4.6'); });
test('explicit principal override never downgrades', () => { const d = selectAgentModeModel(input({ explicitPrincipalOverride: { overrideRef: 'review-1' } })); assert.equal(d.tier, 'principal'); assert.equal(d.reason, 'cost_unknown'); });
test('worker escalates after validated quality failure', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'worker', outcome: 'quality_failure' }, taskClass: 'worker' })); assert.equal(d.tier, 'senior'); assert.equal(d.reason, 'validated_reasoning_failure'); });
test('provider failure does not escalate', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'worker', outcome: 'provider_failure' } })); assert.equal(d.tier, 'worker'); assert.equal(d.ok, true); });
test('senior validation failure escalates to principal but remains cost gated', () => { const d = selectAgentModeModel(input({ previousAttempt: { tier: 'senior', outcome: 'validation_failure' } })); assert.equal(d.tier, 'principal'); assert.equal(d.reason, 'cost_unknown'); });
test('context limit promotes worker to senior', () => { const d = selectAgentModeModel(input({ requiredContextTokens: 196001 })); assert.equal(d.tier, 'senior'); assert.equal(d.reason, 'context_limit'); });
test('output limit promotes worker to senior', () => { const d = selectAgentModeModel(input({ requiredOutputTokens: 8001 })); assert.equal(d.tier, 'senior'); assert.equal(d.reason, 'output_limit'); });
test('principal context overflow is terminal', () => { const d = selectAgentModeModel(input({ taskClass: 'principal', requiredContextTokens: 1000001 })); assert.equal(d.ok, false); assert.equal(d.reason, 'context_limit'); });
test('stale evidence denies without probing', () => { const d = selectAgentModeModel(input({ routeEvidence: evidence({ freshUntil: '2026-09-09T11:59:59.000Z' }) })); assert.equal(d.ok, false); assert.equal(d.reason, 'evidence_stale'); });
test('unknown evidence denies', () => { const d = selectAgentModeModel(input({ routeEvidence: evidence({ state: 'unknown' }) })); assert.equal(d.ok, false); assert.equal(d.reason, 'route_unavailable'); });
test('unavailable evidence denies', () => { const d = selectAgentModeModel(input({ routeEvidence: evidence({ state: 'unavailable' }) })); assert.equal(d.ok, false); assert.equal(d.reason, 'route_unavailable'); });
test('degraded evidence is admitted with explicit reason', () => { const d = selectAgentModeModel(input({ routeEvidence: evidence({ state: 'degraded' }) })); assert.equal(d.ok, true); assert.equal(d.reason, 'route_degraded'); });
test('denied access is fail closed', () => { const d = selectAgentModeModel(input({ routeEvidence: evidence({ accessState: 'denied' }) })); assert.equal(d.ok, false); assert.equal(d.reason, 'evidence_stale'); });
test('child cannot bypass root budget scope', () => { const d = selectAgentModeModel(input({ parentBudgetScopeId: 'child-1' })); assert.equal(d.ok, false); assert.equal(d.reason, 'invalid_scope'); });
test('budget estimate is deterministic and reservation-shaped', () => { const d = selectAgentModeModel(input({ inputTokens: 1234, outputTokens: 4321 })); assert.equal(d.budgetReservation.tokens, 5555); assert.equal(d.budgetReservation.dollars, d.estimatedCostUsd); });
test('dollar budget denies an over-budget admitted model', () => { const d = selectAgentModeModel(input({ maxDollars: 0 })); assert.equal(d.ok, false); assert.equal(d.reason, 'budget_exhausted'); });
test('local or unadmitted route evidence cannot enter portfolio', () => { const bad = { ...evidence(), 'agent-mode/minimax-m2.5': { ...evidence()['agent-mode/minimax-m2.5'], routeId: 'ollama/qwen' } }; const d = selectAgentModeModel(input({ routeEvidence: bad })); assert.equal(d.ok, false); assert.equal(d.reason, 'unadmitted_model'); });

test('Codex available admits with fresh evidence', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 10, now, evidence: { state: 'available', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, true); });
test('Codex constrained honors manual reserve', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 10, now, evidence: { state: 'constrained', remainingTokens: 100, manualReserveTokens: 50, checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, true); });
test('Codex constrained rejects reserve breach', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 51, now, evidence: { state: 'constrained', remainingTokens: 100, manualReserveTokens: 50, checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, false); });
test('Codex exhausted rejects automatic admission', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 1, now, evidence: { state: 'exhausted', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, false); });
test('Codex unknown rejects automatic admission', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 1, now, evidence: { state: 'unknown', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, false); });
test('Codex human override is explicit and bounded', () => { assert.equal(admitCodexResource({ mode: 'human_override', estimatedTokens: 1, overrideRef: 'human-1', now, evidence: { state: 'unknown', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T13:00:00Z' } }).ok, true); });
test('Codex stale evidence rejects even available state', () => { assert.equal(admitCodexResource({ mode: 'automatic', estimatedTokens: 1, now, evidence: { state: 'available', checkedAt: '2026-09-09T11:00:00Z', freshUntil: '2026-09-09T11:59:00Z' } }).ok, false); });
