import test from 'node:test';
import assert from 'node:assert/strict';
import { applyExactScopeFixture, hashExactScopeContent, previewExactScopeApply, validateExactScopeApproval, ExactScopeApprovalError, type ExactScopeApproval, type ExactScopeProposal } from '../adapters/infinite-brain-exact-scope-approval.js';

const before = '# Before\n';
const baseApproval = (): ExactScopeApproval => ({ approvalId: 'approval-1', approvedBy: 'trusted-operator', approvedAt: '2026-07-15T10:00:00.000Z', expiresAt: '2099-07-16T10:00:00.000Z', idempotencyKey: 'idem-1', files: [{ path: 'fixtures/current.md', beforeHash: hashExactScopeContent(before), sections: [{ startLine: 1, endLine: 2 }] }], rollback: { 'fixtures/current.md': { required: true, strategy: 'restore-before-content', beforeHash: hashExactScopeContent(before) } } });
const baseProposal = (): ExactScopeProposal => ({ requestId: 'request-1', idempotencyKey: 'idem-1', rollbackRequired: true, changes: [{ path: 'fixtures/current.md', beforeHash: hashExactScopeContent(before), afterContent: '# After\n', sections: [{ startLine: 1, endLine: 2 }] }] });
const expectCode = (code: string, fn: () => unknown) => assert.throws(fn, (error: unknown) => error instanceof ExactScopeApprovalError && error.code === code);

test('exact approval validates and preview is deterministic', () => { const a = baseApproval(); const p = baseProposal(); assert.ok(validateExactScopeApproval(a, p, new Date('2026-07-15T12:00:00Z'))); assert.deepEqual(previewExactScopeApply(a, p, new Date('2026-07-15T12:00:00Z')), previewExactScopeApply(a, p, new Date('2026-07-15T12:00:00Z'))); });
test('fixture apply succeeds once and identical retry is idempotent', () => { const contents = new Map([['fixtures/current.md', before]]); const consumed = new Map(); const first = applyExactScopeFixture({ approval: baseApproval(), proposal: baseProposal(), contents, consumed, now: new Date('2026-07-15T12:00:00Z') }); const second = applyExactScopeFixture({ approval: baseApproval(), proposal: baseProposal(), contents, consumed, now: new Date('2026-07-15T12:00:00Z') }); assert.equal(first.status, 'applied'); assert.equal(second.status, 'idempotent-replay'); assert.equal(contents.get('fixtures/current.md'), '# After\n'); assert.equal(first.files[0]?.rollback.required, true); });
test('unapproved extra path fails closed', () => { const p = baseProposal(); p.changes.push({ ...p.changes[0]!, path: 'fixtures/extra.md' }); expectCode('file_scope_mismatch', () => validateExactScopeApproval(baseApproval(), p)); });
test('path traversal and normalized substitution fail closed', () => { const p = baseProposal(); p.changes[0]!.path = 'fixtures/../current.md'; expectCode('path_scope_mismatch', () => validateExactScopeApproval(baseApproval(), p)); });
test('changed before hash fails closed', () => { const p = baseProposal(); p.changes[0]!.beforeHash = 'changed'; expectCode('before_hash_mismatch', () => validateExactScopeApproval(baseApproval(), p)); });
test('unapproved section fails closed', () => { const p = baseProposal(); p.changes[0]!.sections = [{ startLine: 3, endLine: 4 }]; expectCode('section_scope_mismatch', () => validateExactScopeApproval(baseApproval(), p)); });
test('expired approval fails closed', () => {
  const approval = baseApproval();
  approval.expiresAt = '2026-07-14T00:00:00Z';
  expectCode('approval_expired', () => validateExactScopeApproval(approval, baseProposal(), new Date('2026-07-17T00:00:00Z')));
});
test('same idempotency key with changed content fails closed', () => { const contents = new Map([['fixtures/current.md', before]]); const consumed = new Map(); applyExactScopeFixture({ approval: baseApproval(), proposal: baseProposal(), contents, consumed, now: new Date('2026-07-15T12:00:00Z') }); const changed = baseProposal(); changed.changes[0]!.afterContent = '# Different\n'; expectCode('idempotency_conflict', () => applyExactScopeFixture({ approval: baseApproval(), proposal: changed, contents, consumed, now: new Date('2026-07-15T12:00:00Z') })); });
test('consumed approval cannot be replayed under a new key', () => { const contents = new Map([['fixtures/current.md', before]]); const consumed = new Map(); applyExactScopeFixture({ approval: baseApproval(), proposal: baseProposal(), contents, consumed, now: new Date('2026-07-15T12:00:00Z') }); const a = baseApproval(); a.idempotencyKey = 'idem-2'; const p = baseProposal(); p.idempotencyKey = 'idem-2'; expectCode('approval_replay', () => applyExactScopeFixture({ approval: a, proposal: p, contents, consumed, now: new Date('2026-07-15T12:00:00Z') })); });
test('missing or weakened rollback fails closed', () => { const a = baseApproval(); delete a.rollback['fixtures/current.md']; expectCode('rollback_scope_mismatch', () => validateExactScopeApproval(a, baseProposal())); });
test('model-supplied approver identity fails closed', () => { const p = baseProposal(); p.modelSupplied = { approvedBy: 'model' }; expectCode('model_supplied_authorization', () => validateExactScopeApproval(baseApproval(), p)); });
test('model-supplied scope broadening fails closed', () => { const p = baseProposal(); p.modelSupplied = { files: ['other.md'] }; expectCode('model_supplied_authorization', () => validateExactScopeApproval(baseApproval(), p)); });
test('repository state change blocks fixture apply', () => { const contents = new Map([['fixtures/current.md', '# Changed\n']]); expectCode('repository_state_changed', () => applyExactScopeFixture({ approval: baseApproval(), proposal: baseProposal(), contents, consumed: new Map(), now: new Date('2026-07-15T12:00:00Z') })); });
