import { test } from "node:test";
import assert from "node:assert";
import { createRuntimeSchedulerLifecycleManifest, renderRuntimeSchedulerLifecycleManifest } from "./video-orchestrator-runtime-scheduler-lifecycle-manifest.js";

test("VO-7FT-RUNTIME-SCHEDULER-LIFECYCLE-MANIFEST-1: lists runtime scheduler lifecycle stages without side effects", () => {
  const manifest = createRuntimeSchedulerLifecycleManifest();

  assert.equal(manifest.schema_version, "1.0");
  assert.equal(manifest.manifest_only, true);
  assert.equal(manifest.stages.length >= 10, true);
  assert.equal(manifest.stages.some((stage) => stage.id === "cli-entrypoint"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "terminal-summary"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "handoff-artifacts-manifest"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "package-script-installed"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-approval"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-contract"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-adapter-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-adapter-skeleton"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-fixture"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-validation"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-review-summary"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-implementation-design"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-implementation-scaffold-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-integration-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-integration-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-integration-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-integration-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-pure-scaffold-integration-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-executable-integration-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-executable-integration-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-executable-integration-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-executable-integration-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-executable-integration-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-implementation-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-implementation-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-implementation-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-implementation-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-implementation-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-code-wiring-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-code-wiring-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-code-wiring-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-code-wiring-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-code-wiring-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-plan"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-review"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-terminal-handoff"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-operator-decision"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-decision-closeout"), true);
  assert.equal(manifest.stages.some((stage) => stage.id === "persistent-store-runtime-import-patch-application-plan"), true);
  assert.equal(manifest.stages.every((stage) => stage.side_effects_enabled === false), true);
  assert.equal(manifest.manual_boundaries.length, 4);
  assert.equal(manifest.safety.package_json_edited, true);
  assert.equal(manifest.safety.live_scheduler_executed, false);
  assert.equal(manifest.safety.upload_executed, false);
  assert.equal(manifest.safety.network_calls_made, false);
  assert.equal(manifest.safety.credential_accessed, false);
  assert.equal(manifest.safety.media_read_performed, false);
  assert.equal(manifest.safety.files_written, false);
  assert.equal(manifest.safety.git_add_executed, false);
  assert.equal(manifest.safety.committed_now, false);
  assert.equal(manifest.safety.pushed_now, false);
});

test("VO-7FT-RUNTIME-SCHEDULER-LIFECYCLE-MANIFEST-2: marks manual boundary stages", () => {
  const manifest = createRuntimeSchedulerLifecycleManifest();
  const boundaryIds = manifest.stages.filter((stage) => stage.state === "manual_boundary").map((stage) => stage.id);

  assert.equal(boundaryIds.includes("package-script-approval-gate"), true);
  assert.equal(boundaryIds.includes("release-checklist"), true);
  assert.equal(boundaryIds.includes("release-handoff"), true);
  assert.equal(boundaryIds.includes("handoff-artifacts-manifest"), true);
  assert.equal(boundaryIds.includes("release-archive"), true);
  assert.equal(boundaryIds.includes("terminal-summary"), true);
  assert.equal(boundaryIds.includes("persistent-store-approval"), true);
  assert.equal(boundaryIds.includes("persistent-store-contract"), true);
  assert.equal(boundaryIds.includes("persistent-store-adapter-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-adapter-skeleton"), true);
  assert.equal(boundaryIds.includes("persistent-store-fixture"), true);
  assert.equal(boundaryIds.includes("persistent-store-validation"), true);
  assert.equal(boundaryIds.includes("persistent-store-review-summary"), true);
  assert.equal(boundaryIds.includes("persistent-store-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-implementation-design"), true);
  assert.equal(boundaryIds.includes("persistent-store-implementation-scaffold-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-integration-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-integration-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-integration-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-integration-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-pure-scaffold-integration-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-executable-integration-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-executable-integration-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-executable-integration-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-executable-integration-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-executable-integration-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-implementation-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-implementation-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-implementation-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-implementation-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-implementation-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-code-wiring-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-code-wiring-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-code-wiring-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-code-wiring-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-code-wiring-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-plan"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-review"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-terminal-handoff"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-operator-decision"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-decision-closeout"), true);
  assert.equal(boundaryIds.includes("persistent-store-runtime-import-patch-application-plan"), true);
});

test("VO-7FU-RUNTIME-SCHEDULER-LIFECYCLE-MANIFEST-REVIEW-1: renderer is safe and explicit", () => {
  const text = renderRuntimeSchedulerLifecycleManifest(createRuntimeSchedulerLifecycleManifest());

  assert.equal(text.includes("runtime scheduler lifecycle manifest"), true);
  assert.equal(text.includes("Package metadata changes require separate explicit approval; the summary-only runtime scheduler package script has been approved and installed."), true);
  assert.equal(text.includes("Live scheduler activation requires separate explicit approval."), true);
  assert.equal(text.includes("persistent-store approval, contract, adapter-plan, adapter-skeleton, dry-run fixture, validation, review-summary, terminal-handoff, operator-decision, decision-closeout, implementation-design, scaffold-plan, pure-scaffold, pure-scaffold-review, pure-scaffold-terminal-handoff, pure-scaffold-operator-decision, pure-scaffold-decision-closeout, pure-scaffold-integration-plan, pure-scaffold-integration-review, pure-scaffold-integration-terminal-handoff, pure-scaffold-integration-operator-decision, pure-scaffold-integration-decision-closeout, executable-integration-plan, executable-integration-review, executable-integration-terminal-handoff, executable-integration-operator-decision, executable-integration-decision-closeout, runtime-import-plan, runtime-import-review, runtime-import-terminal-handoff, runtime-import-operator-decision, runtime-import-decision-closeout, runtime-import-implementation-plan, runtime-import-implementation-review, runtime-import-implementation-terminal-handoff, runtime-import-implementation-operator-decision, runtime-import-implementation-decision-closeout, runtime-import-code-wiring-plan, runtime-import-code-wiring-review, runtime-import-code-wiring-terminal-handoff, runtime-import-code-wiring-operator-decision, runtime-import-code-wiring-decision-closeout, runtime-import-patch-plan, runtime-import-patch-review, runtime-import-patch-terminal-handoff, runtime-import-patch-operator-decision, runtime-import-patch-decision-closeout, and runtime-import-patch-application-plan packets are available"), true);
  assert.equal(text.includes("package.json edited: true"), true);
  assert.equal(text.includes("Live scheduler executed: false"), true);
  assert.equal(text.includes("access_token"), false);
  assert.equal(text.includes("client_secret"), false);
  assert.equal(text.includes("api_key"), false);
});
